### <개발 방법>
- > 계획(기획, 주제 어느정도 선정) 
- > 요구분석 
- > 설계 
- > 구현 
- > 테스트 
- > 운영(서비스)

### <분석 방법>
- > 계획(기획, 주제 정해져 있지 않음)
- > 요구분석 > 데이터 수집
- > 데이터 전처리(1차: 이상치, 결측치, 중복치 확인 / 2차: 만들어낸 데이터 조합(시간 데이터가 있는지 확인! ★★★))
- > 1차 인사이트 도출 분석(EDA)(데이터 시각화)
- > 데이터 후처리(필요 데이터만 추출 / 문자 데이터를 숫자 데이터로 후처리)
- > 데이터 모델링(모델 훈련)
- > 2차 모델링 선정 분석
- > 서비스화를 위한 엔지니어링(MLOps + DevOps) + 개발의 프로세스

#### 기본적으로 알아야 하는 용어

##### <데이터의 종류>
- 정형 데이터 : 행렬도 가동된(또는 가공이 가능한) 데이터
- 반정형 데이터 : 프로그램 처리를 통해 정형데이터로 가공이 가능한 데이터(html tag 데이터, xml tag 데이터)
- 비정형 데이터 : 행렬로 가공이 어려운 데이터(뉴스 기사, 음성 데이터, 영상 데이터, 문서 등등...)

##### <학습의 종류>
- 지도 학습 : 정형데이터에서 예측에 필요한 정답을 알고 있는 경우
- 비지도 학습 : 정형/비정형 데이터에서 예측에 필요한 정답을 모르고 있는 경우(문제만 주고 답은 알아서 맞춰라)

##### <분석 방법>
- 회귀(선형)분석 : 지도학습 (연속형 데이터 형태 예측)
- 분류(판단)분석 : 지도학습 (범주형 데이터 형태 예측)
- 군집분석(분류분석) : 비지도학습(정답이 없음)

---
y(종속변수=정답) = a * x(독립변수=문제) + b

### 사용할 라이브러리 불러들이기

In [ ]:
import pandas as pd

- 절대경로 : 드라이브 이름부터의 경로
- : D:\pknu_202610\01_Machine_Learning\2day_Data_Preprocess\dataset
- 상대경로 : 현재 작업중인 파일의 위치를 시작점으로 경로설정
- : ./dataset

### 사용할 데이터셋 읽어들이기

In [ ]:
### 1. 사용할 데이터셋 파일 : 01_02_ecommerce_customers_noisy.csv
### 2. 읽어들인 데이터는 df라는 데이터프레임 변수에 저장시키기
df = pd.read_csv('./dataset/01_02_ecommerce_customers_noisy.csv')
df.head() #df는 클래스 변수라서 뒤에 `.` 을 붙여서 함수 실행

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,1,56.0,Male,49,95.19,473910.0,7,3.3,0
1,2,69.0,Female,70,108.39,712146.0,1,4.4,0
2,3,46.0,Female,49,73.39,381329.0,7,1.7,1
3,4,32.0,Male,3,44.06,13888.0,4,4.6,1
4,5,60.0,Male,5,132.83,69017.0,7,3.0,1

In [ ]:
# 선생님 방법
file_path = "./dataset/01_02_ecommerce_customers_noisy.csv"
pd.read_csv(file_path)

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,1,56.0,Male,49,95.19,473910.00,7,3.3,0
1,2,69.0,Female,70,108.39,712146.00,1,4.4,0
2,3,46.0,Female,49,73.39,381329.00,7,1.7,1
3,4,32.0,Male,3,44.06,13888.00,4,4.6,1
4,5,60.0,Male,5,132.83,69017.00,7,3.0,1
...,...,...,...,...,...,...,...,...,...
4995,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4996,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4997,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4998,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4999,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
# 컬럼명 바꾸기
df.columns = [    '고객 고유 식별자', 
    '고객 나이', 
    '고객 성별', 
    '가입 기간_월단위', 
    '월 평균 결제액', 
    '총 결제액', 
    '고객센터 문의 횟수', 
    '리뷰 평균 점수', 
    '이탈 여부']

df

,고객 고유 식별자,고객 나이,고객 성별,가입 기간_월단위,월 평균 결제액,총 결제액,고객센터 문의 횟수,리뷰 평균 점수,이탈 여부
0,1,56.0,Male,49,95.19,473910.00,7,3.3,0
1,2,69.0,Female,70,108.39,712146.00,1,4.4,0
2,3,46.0,Female,49,73.39,381329.00,7,1.7,1
3,4,32.0,Male,3,44.06,13888.00,4,4.6,1
4,5,60.0,Male,5,132.83,69017.00,7,3.0,1
...,...,...,...,...,...,...,...,...,...
4995,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4996,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4997,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4998,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4999,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

### 데이터셋 정보 확인하기

In [ ]:
### info() : 결측치 확인이 가능한 함수(매우 중요)
# RangeIndex > 각 컬럼의 Non-Null Count 인 경우 결측치가 있다고 판단
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             4750 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  4850 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

### 데이터셋 기초 통계

In [ ]:
### 이상치를 확인 가능: 단, 컬럼의 성격을 어느정도 알고 있다는 전제 하에 이상치에 대해서 1차 확인 가능
# - min or max 값으로 확인 가능
df.describe()

,CustomerID,Age,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
count,5000.000000,4750.000000,5000.000000,4850.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,43.844421,36.611400,79.941992,3635.135300,4.990600,2.967340,0.401800
std,1443.520003,15.711242,20.839569,40.167056,21261.950661,3.119304,1.140677,0.490311
min,1.000000,18.000000,1.000000,10.020000,9.520000,0.000000,1.000000,0.000000
25%,1250.750000,31.000000,18.000000,45.575000,989.962500,2.000000,2.000000,0.000000
50%,2500.500000,44.000000,36.500000,80.175000,2245.985000,5.000000,3.000000,0.000000
75%,3750.250000,56.000000,55.000000,114.007500,4331.892500,8.000000,3.900000,1.000000
max,5000.000000,150.000000,72.000000,149.980000,874657.000000,10.000000,5.000000,1.000000

### 대용량 데이터를 사용하는 경우에는 샘플링을 위한 데이터만 추출하여
##### - 먼저 기본 데이터를 처리한 후 향후 전체 데이터를 사용

In [ ]:
### 샘플링 데이터 읽어들이기
# - chunksize(행의 갯수) : 추출한 갯수 설정
# - 반환 타입은 이터레이터(Iterator) 타입
df_temp = pd.read_csv(file_path, chunksize=1000)

# 이터레이터 타입을 데이터 프레임 타입으로 변환
df_temp = next(df_temp)
df_temp

### 필요한 컬럼만 추출해서 읽어들이기
df_temp = pd.read_csv(file_path, usecols=["CustomerID", "Age", "Gender"])
df_temp

      CustomerID   Age  Gender
0              1  56.0    Male
1              2  69.0  Female
2              3  46.0  Female
3              4  32.0    Male
4              5  60.0    Male
...          ...   ...     ...
4995        4996  24.0    Male
4996        4997  66.0  Female
4997        4998  26.0  Female
4998        4999  53.0  Female
4999        5000  36.0  Female

[5000 rows x 3 columns]

In [ ]:
df.info()

# 함수 매개변수에 비워있는 경우에는
# Dtype이 숫자 형태에 대해서만 통계를 하며, object 및 category 타입은 제외시킴
df.describe() #Gender 빠져있음.

# 컬럼의 Dtype 별로 기초통계 조회 가능
df.describe(include=["int", "float", "object"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             4750 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  4850 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
count,5000.000000,4750.000000,5000,5000.000000,4850.000000,5000.000000,5000.000000,5000.000000,5000.000000
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,2514,NaN,NaN,NaN,NaN,NaN,NaN
mean,2500.500000,43.844421,NaN,36.611400,79.941992,3635.135300,4.990600,2.967340,0.401800
std,1443.520003,15.711242,NaN,20.839569,40.167056,21261.950661,3.119304,1.140677,0.490311
min,1.000000,18.000000,NaN,1.000000,10.020000,9.520000,0.000000,1.000000,0.000000
25%,1250.750000,31.000000,NaN,18.000000,45.575000,989.962500,2.000000,2.000000,0.000000
50%,2500.500000,44.000000,NaN,36.500000,80.175000,2245.985000,5.000000,3.000000,0.000000
75%,3750.250000,56.000000,NaN,55.000000,114.007500,4331.892500,8.000000,3.900000,1.000000
max,5000.000000,150.000000,NaN,72.000000,149.980000,874657.000000,10.000000,5.000000,1.000000

### 범주형 데이터의 고유값 조회하기

In [ ]:
### Churn 컬럼의 고유값과 고유값별 갯수(count) 확인하기 / value_counts ★
df.value_counts("Churn")

chrun_cnt = df["Churn"].value_counts()
print("이탈여부 범주 구성", chrun_cnt)


chrun_cnt = df["Churn"].value_counts(normalize=True)
print("이탈여부 범주별 비율", chrun_cnt)

### Gender 컬럼의 고유값과 고유값별 갯수 확인하기
df.value_counts("Gender")

gender_cnt = df["Gender"].value_counts()
print("성별 구성", gender_cnt)


gender_cnt = df["Gender"].value_counts(normalize=True)
print("성별 구성 비율", gender_cnt)

이탈여부 범주 구성 Churn
0    2991
1    2009
Name: count, dtype: int64
이탈여부 범주별 비율 Churn
0    0.5982
1    0.4018
Name: proportion, dtype: float64
성별 구성 Gender
Female    2514
Male      2486
Name: count, dtype: int64
성별 구성 비율 Gender
Female    0.5028
Male      0.4972
Name: proportion, dtype: float64

## [분류/회귀] 결측치 탐지 및 상황별 대체 기법

- 데이터셋 내에 결측(NaN) 데이터는 머신러닝 알고리즘에서 에러의 주요 원인이 됨

In [ ]:
### df 데이터셋에 결측데이터 확인하기
# - 컬럼별 결측치의 총갯수 확인하기
df.isna().sum()

CustomerID          0
Age               250
Gender              0
Tenure              0
MonthlyCharges    150
TotalCharges        0
SupportCalls        0
ReviewScore         0
Churn               0
dtype: int64

In [ ]:
### Age 나이 컬럼의 데이터 중에 결측(누락) 데이터들을 모두
# -Age의 중앙값으로 대체해 주세요


# 1. 대체할 중앙값 추출하기
age_median = df["Age"].median()
df["Age"].fillna(age_median)

df["Age"] = df["Age"].fillna(age_median)
df.isna().sum()

CustomerID          0
Age                 0
Gender              0
Tenure              0
MonthlyCharges    150
TotalCharges        0
SupportCalls        0
ReviewScore         0
Churn               0
dtype: int64

In [ ]:
### MonthlyCharges 컬럼의 데이터 중에 결측(누락) 데이터들을 모두
# - MonthlyCharges의 평균으로 대체해 주세요

MC_Mean = df["MonthlyCharges"].mean()
df["MonthlyCharges"].fillna(MC_Mean)

df["MonthlyCharges"] = df["MonthlyCharges"].fillna(MC_Mean)

df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             5000 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  5000 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

CustomerID        0
Age               0
Gender            0
Tenure            0
MonthlyCharges    0
TotalCharges      0
SupportCalls      0
ReviewScore       0
Churn             0
dtype: int64

### [회귀/분류] 이상치(Outliter) 탐지(IQR, Z-Score) 및 처리
- 회귀분석용 이상치 처리: Z-Score 방법 적용 -> 보통 이상치는 제거(대체가 가능하면 대체)
- 분류분석용 이상치 처리 : IQR 방법 적용 -> 보통 이상치는 제거(대체가 가능하면 대체)

In [ ]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,1,56.0,Male,49,95.19,473910.00,7,3.3,0
1,2,69.0,Female,70,108.39,712146.00,1,4.4,0
2,3,46.0,Female,49,73.39,381329.00,7,1.7,1
3,4,32.0,Male,3,44.06,13888.00,4,4.6,1
4,5,60.0,Male,5,132.83,69017.00,7,3.0,1
...,...,...,...,...,...,...,...,...,...
4995,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4996,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4997,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4998,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4999,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

## 회귀 분석용 이상치 처리 
- Z-Score 방법으로 이상치 찾기

In [ ]:
import numpy as np

In [1]:
# 선형(주로 선형 데이터에서 사용)회귀는 정규 분포 가정을 따름으로,
#  - 평균으로부터 표준편차의 몇 배만큼 떨어져 있는지를 나타내는 Z-Score를 사용함
# Z = (X - μ) / σ (X: 데이터 포인트, μ: 평균, σ: 표준편차)
# Z보다 큰(초과) 값들은 이상치로 판단(작은 값이 정상 데이터)


### TotalCharges 데이터에서 이상치 유무 확인하기
# - X = TotalCharges 데이터가 됨
z_score = np.abs((df["TotalCharges"] - df["TotalCharges"].mean()) / df["TotalCharges"].std())
print(z_score)

### 이상치 기준을 결정하기
# Z-Score의 값이 3(약 99.7% 신뢰구간을 의미함) 이상인 데이터를 이상치로 규정함
# Z-Score는 신뢰구간을 나타내는 값을 의미함

### 이상치 제거 전 df 정보 : 전체 5000건
print("----------[Z-Score 이상치 처리 전]-----------")
df.info()

### 이상치 제거 처리 : z_score 값이 3보다 작은 경우의 행인덱스 위치의 값만 추출
###                 : 이상치 제거 효과와 동일

# 데이터 행단위 필터링(조건정리)
df = df[z_score < 3]
print("----------[Z-Score 이상치 처리 후]-----------")
df.info()

NameError: name 'np' is not defined

In [ ]:
df.describe()

,CustomerID,Age,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
count,4979.000000,4979.000000,4979.000000,4979.000000,4979.000000,4979.000000,4979.000000,4979.000000
mean,2505.944165,43.859008,36.549508,79.778807,2880.798421,4.989757,2.967162,0.401085
std,1439.913429,15.318574,20.791937,39.479145,2342.428681,3.119119,1.139839,0.490167
min,12.000000,18.000000,1.000000,10.020000,9.520000,0.000000,1.000000,0.000000
25%,1259.500000,32.000000,18.000000,46.475000,983.970000,2.000000,2.000000,0.000000
50%,2507.000000,44.000000,36.000000,79.941992,2234.010000,5.000000,3.000000,0.000000
75%,3751.500000,56.000000,55.000000,112.650000,4294.460000,8.000000,3.900000,1.000000
max,5000.000000,150.000000,72.000000,149.980000,10354.290000,10.000000,5.000000,1.000000

## 분류 분석용 이상치 처리 - IQR(InterQuartile Range)
- 박스플롯(boxplolt) 기반 이상치 탐지 방식임
- IQR = Q3-Q1
- Max-Out = 75%사분위수값 Q3 + 1.5 * IQR
- Min-Out = 25%사분위수값 Q1- 1.5 * IQR

In [ ]:

# 비선형 및 범주형일 경우 IQR사용
# 난 아무것도 모르겠다! IQR로 사용
### Q1 및 Q3 값 추출하기
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)
print(f"Q1={Q1}, Q3={Q3}")

### IQR 계산하기
IQR = Q3 - Q1
print(f"IQR={IQR}")

### Max-Out = 75%사분위수값 Q3 + 1.5 * IQR
### Min-Out = 25%사분위수값 Q1- 1.5 * IQR
lower_bound = Q1-1.5 * IQR 
upper_bound = Q3+1.5 * IQR
print(f"lower_bound={lower_bound}, upper_bound={upper_bound}")

Q1=32.0, Q3=56.0
IQR=24.0
lower_bound=-4.0, upper_bound=92.0

In [ ]:
### IQR 이상치 처리 : lower_bound 이상이고, upper_bound 이하인 데이터만 추출하여 df에 넣기
df = df[(df["Age"] >= lower_bound) & (df["Age"] <= upper_bound)] # and 연산자는 괄호써줘야함.

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4982 entries, 3 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      4982 non-null   int64
 1   Age             4982 non-null   float64
 2   Gender          4982 non-null   object
 3   Tenure          4982 non-null   int64
 4   MonthlyCharges  4982 non-null   float64
 5   TotalCharges    4982 non-null   float64
 6   SupportCalls    4982 non-null   int64
 7   ReviewScore     4982 non-null   float64
 8   Churn           4982 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 389.2+ KB

In [ ]:
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
3,4,True,Male,3,44.06,13888.00,4,4.6,1
9,10,True,Female,15,36.90,50671.00,1,2.2,0
10,11,True,Female,16,22.14,36716.00,5,1.2,1
11,12,False,Female,1,57.18,55.48,2,1.9,0
12,13,False,Male,16,28.06,424.25,7,2.1,1
...,...,...,...,...,...,...,...,...,...
4995,4996,True,Male,17,131.19,2441.28,7,1.8,0
4996,4997,True,Female,5,31.12,164.20,2,1.3,1
4997,4998,True,Female,18,11.80,199.44,4,3.5,0
4998,4999,True,Female,55,25.40,1455.62,5,2.6,0
4999,5000,True,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
### 인덱스 번호를 순차적으로 다시 재정의하기 (0부터~~)
#df.reset_index()

#inplace=True : 처리와 동시에 해당 데이터프레임 메모리에 반영시키기
df.reset_index(inplace=True, drop=True)
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,4,32.0,Male,3,44.06,13888.00,4,4.6,1
1,10,40.0,Female,15,36.90,50671.00,1,2.2,0
2,11,28.0,Female,16,22.14,36716.00,5,1.2,1
3,22,47.0,Male,54,117.37,6880.05,5,1.8,0
4,23,55.0,Male,27,68.26,1736.67,0,2.3,0
...,...,...,...,...,...,...,...,...,...
4977,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4978,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4979,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4980,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4981,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

## 데이터 타입 변환 및 문자열 처리

In [ ]:


### Age 나이 타입을 정수타입으로 변경하기
df["Age"] = df["Age"].astype("int")

df.info()
df.tail(4)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4982 entries, 0 to 4981
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      4982 non-null   int64
 1   Age             4982 non-null   int64
 2   Gender          4982 non-null   object
 3   Tenure          4982 non-null   int64
 4   MonthlyCharges  4982 non-null   float64
 5   TotalCharges    4982 non-null   float64
 6   SupportCalls    4982 non-null   int64
 7   ReviewScore     4982 non-null   float64
 8   Churn           4982 non-null   int64
dtypes: float64(3), int64(5), object(1)
memory usage: 350.4+ KB

C:\Users\User\AppData\Local\Temp\ipykernel_35264\4052678929.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].astype("int")

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
4978,4997,66,Female,5,31.12,164.20,2,1.3,1
4979,4998,26,Female,18,11.80,199.44,4,3.5,0
4980,4999,53,Female,55,25.40,1455.62,5,2.6,0
4981,5000,36,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
### Gender 성별의 영문자를 모두 소문자로 

# str : 데이터프레임의 각 문자열값에 대한 함수를 적용하기 위해서 str(문자타입) 정의 후 함수 사용
# lower(소문자 변환): 문자열 함수 -> str.lower() 사용
# upper(대문자 변환): 문자열 함수 -> str.upper() 사용
df["Gender"] = df["Gender"].str.lower()
df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_35264\368464854.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].str.lower()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,4,32,male,3,44.06,13888.00,4,4.6,1
1,10,40,female,15,36.90,50671.00,1,2.2,0
2,11,28,female,16,22.14,36716.00,5,1.2,1
3,22,47,male,54,117.37,6880.05,5,1.8,0
4,23,55,male,27,68.26,1736.67,0,2.3,0

## [일괄 처리 함수 사용]

In [ ]:
"""
1. noisy.csv 파일 읽어드리기
2. 전처리 함수 생성하기
    - 함수명 : clean_ecommerce_data
    - 처리 내용 : 지금까지 전처리했던 모든 것..
    - 반환값 : 전처리가 끝난 데이터프레임
3. 전처리 함수 호출하여 전처리 결과값 받아오기
4. 전처리 결과 데이터프레임을 파일로 저장하기
    - 저장 위치 : dataset
    - 저장 파일명 : 01_03_clean_ecommerce_data_clean.csv
    - 저장 시 사용하는 함수 : 데이터프레임.to_csv() 함수 사용하여 저장
"""

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
file_path = "./dataset/01_02_ecommerce_customers_noisy.csv"
df = pd.read_csv(file_path)
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,1,56.0,Male,49,95.19,473910.00,7,3.3,0
1,2,69.0,Female,70,108.39,712146.00,1,4.4,0
2,3,46.0,Female,49,73.39,381329.00,7,1.7,1
3,4,32.0,Male,3,44.06,13888.00,4,4.6,1
4,5,60.0,Male,5,132.83,69017.00,7,3.0,1
...,...,...,...,...,...,...,...,...,...
4995,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4996,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4997,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4998,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4999,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             4750 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  4850 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

In [ ]:
df.isna().sum()

CustomerID          0
Age               250
Gender              0
Tenure              0
MonthlyCharges    150
TotalCharges        0
SupportCalls        0
ReviewScore         0
Churn               0
dtype: int64

In [ ]:
age_median = df["Age"].median()
df["Age"] = df["Age"].fillna(age_median)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             5000 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  4850 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

In [ ]:
mc_mean = df["MonthlyCharges"].mean()
df["MonthlyCharges"] = df["MonthlyCharges"].fillna(mc_mean)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      5000 non-null   int64
 1   Age             5000 non-null   float64
 2   Gender          5000 non-null   object
 3   Tenure          5000 non-null   int64
 4   MonthlyCharges  5000 non-null   float64
 5   TotalCharges    5000 non-null   float64
 6   SupportCalls    5000 non-null   int64
 7   ReviewScore     5000 non-null   float64
 8   Churn           5000 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 351.7+ KB

In [ ]:
# z-score 3이상인 것들 없애기
# z-score = x - u / std
z_score = np.abs((df["TotalCharges"] - df["TotalCharges"].mean()) / df["TotalCharges"].std())

df = df[z_score < 3]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4979 entries, 11 to 4999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      4979 non-null   int64
 1   Age             4979 non-null   float64
 2   Gender          4979 non-null   object
 3   Tenure          4979 non-null   int64
 4   MonthlyCharges  4979 non-null   float64
 5   TotalCharges    4979 non-null   float64
 6   SupportCalls    4979 non-null   int64
 7   ReviewScore     4979 non-null   float64
 8   Churn           4979 non-null   int64
dtypes: float64(4), int64(4), object(1)
memory usage: 389.0+ KB

In [ ]:
# IQR 이상치 제거 [Age]
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[(df["Age"] >= lower_bound) & (df["Age"] <= upper_bound)]

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
21,22,47.0,Male,54,117.37,6880.05,5,1.8,0
22,23,55.0,Male,27,68.26,1736.67,0,2.3,0
23,24,44.0,Male,38,12.37,475.20,4,3.4,0
24,25,38.0,Female,58,96.53,5179.77,4,2.5,0
25,26,50.0,Male,62,18.83,1155.14,6,3.7,0
...,...,...,...,...,...,...,...,...,...
4995,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4996,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4997,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4998,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4999,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
df.reset_index(inplace=True, drop=True)
df

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,22,47.0,Male,54,117.37,6880.05,5,1.8,0
1,23,55.0,Male,27,68.26,1736.67,0,2.3,0
2,24,44.0,Male,38,12.37,475.20,4,3.4,0
3,25,38.0,Female,58,96.53,5179.77,4,2.5,0
4,26,50.0,Male,62,18.83,1155.14,6,3.7,0
...,...,...,...,...,...,...,...,...,...
4964,4996,24.0,Male,17,131.19,2441.28,7,1.8,0
4965,4997,66.0,Female,5,31.12,164.20,2,1.3,1
4966,4998,26.0,Female,18,11.80,199.44,4,3.5,0
4967,4999,53.0,Female,55,25.40,1455.62,5,2.6,0
4968,5000,36.0,Female,53,60.91,2953.91,0,1.7,0

In [ ]:
df["Age"] = df["Age"].astype("int")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4969 entries, 0 to 4968
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      4969 non-null   int64
 1   Age             4969 non-null   int64
 2   Gender          4969 non-null   object
 3   Tenure          4969 non-null   int64
 4   MonthlyCharges  4969 non-null   float64
 5   TotalCharges    4969 non-null   float64
 6   SupportCalls    4969 non-null   int64
 7   ReviewScore     4969 non-null   float64
 8   Churn           4969 non-null   int64
dtypes: float64(3), int64(5), object(1)
memory usage: 349.5+ KB

In [ ]:
df["Gender"].str.lower()

0         male
1         male
2         male
3       female
4         male
         ...
4964      male
4965    female
4966    female
4967    female
4968    female
Name: Gender, Length: 4969, dtype: object

In [ ]:
import pandas as pd
import numpy as np


# 읽어오기
file_path = "./dataset/01_02_ecommerce_customers_noisy.csv"
df = pd.read_csv(file_path) #df는 메모리 주소값임. 데이터프레임으로 받은 클래스의 주소값을 받아옴

# 전처리 함수 생성하기 : 사용자 정의 함수(직접 만든 함수를 의미)
# 함수명 : clean_ecommerce_data
# 처리내용 : 지금까지 했던 전처리 모든 것
# 반환값(return) : 전처리 끝난 데이터프레임

### 함수 정의시 고려 사항
# 1. input data : 어떤 데이터를 받아서 사용할지? (없을 수도 있음) / 매개변수(파라미터) : 함수 () 내 작성 
# 2. 처리 프로그램 : 어떤 처리를 할지? (받아오는 데이터가 있다면 이 데이터를 어떻게 사용할지?)
# 3. output data : 최정 결과 데이터를 넘겨 줄지 말지?


def clean_ecommerce_data(df_one):
# ↓ 처리 프로그램///....
    # Age를 중앙값으로 대체
    age_median = df_one["Age"].median()
    df_one["Age"] = df_one["Age"].fillna(age_median)

    # MonthlyCharges를 평균으로 대체
    mc_mean = df_one["MonthlyCharges"].mean()
    df_one["MonthlyCharges"] = df_one["MonthlyCharges"].fillna(mc_mean)

    # z-score 3이상인 것들 없애기
    z_score = np.abs((df_one["TotalCharges"] - df_one["TotalCharges"].mean()) / df_one["TotalCharges"].std())
    df_one = df_one[z_score < 3]

    # IQR 이상치 제거 [Age]
    Q1 = df_one["Age"].quantile(0.25)
    Q3 = df_one["Age"].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_one = df_one[(df_one["Age"] >= lower_bound) & (df_one["Age"] <= upper_bound)]

    # 인덱스 재정의
    df_one.reset_index(inplace=True, drop=True)

    # 나이를 정수형태로
    df_one["Age"] = df_one["Age"].astype("int")

    # 성별을 소문자로
    df_one["Gender"] = df_one["Gender"].str.lower()
    # output data : 반환(return) -> 전처리가 완료된 데이터 프레임 반환
    return df_one

save_path = "./dataset/01_03_clean_ecommerce_data_clean.csv"
df_final=clean_ecommerce_data(df)
df_final.to_csv(save_path, index=False)

In [ ]:
df_final

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,4,32,male,3,44.06,13888.00,4,4.6,1
1,10,40,female,15,36.90,50671.00,1,2.2,0
2,11,28,female,16,22.14,36716.00,5,1.2,1
3,22,47,male,54,117.37,6880.05,5,1.8,0
4,23,55,male,27,68.26,1736.67,0,2.3,0
...,...,...,...,...,...,...,...,...,...
4977,4996,24,male,17,131.19,2441.28,7,1.8,0
4978,4997,66,female,5,31.12,164.20,2,1.3,1
4979,4998,26,female,18,11.80,199.44,4,3.5,0
4980,4999,53,female,55,25.40,1455.62,5,2.6,0
4981,5000,36,female,53,60.91,2953.91,0,1.7,0

In [ ]:
# 함수 실행 후 다음 셀에서 확인해보면?
print(len(df_final))  # ← 이상치가 전혀 제거되지 않고 행 개수가 그대로 남아있습니다!

4982

In [ ]:
##### 추가 학습

import pandas as pd
import numpy as np


# 읽어오기
 #df는 메모리 주소값임. 데이터프레임으로 받은 클래스의 주소값을 받아옴

# 전처리 함수 생성하기 : 사용자 정의 함수(직접 만든 함수를 의미)
# 함수명 : clean_ecommerce_data
# 처리내용 : 지금까지 했던 전처리 모든 것
# 반환값(return) : 전처리 끝난 데이터프레임

### 함수 정의시 고려 사항
# 1. input data : 어떤 데이터를 받아서 사용할지? (없을 수도 있음) / 매개변수(파라미터) : 함수 () 내 작성 
# 2. 처리 프로그램 : 어떤 처리를 할지? (받아오는 데이터가 있다면 이 데이터를 어떻게 사용할지?)
# 3. output data : 최정 결과 데이터를 넘겨 줄지 말지?


def clean_ecommerce_data():
    file_path = "./dataset/01_02_ecommerce_customers_noisy.csv"
    df = pd.read_csv(file_path)

# ↓ 처리 프로그램///....
    # Age를 중앙값으로 대체
    age_median = df["Age"].median()
    df["Age"] = df["Age"].fillna(age_median)

    # MonthlyCharges를 평균으로 대체
    mc_mean = df["MonthlyCharges"].mean()
    df["MonthlyCharges"] = df["MonthlyCharges"].fillna(mc_mean)

    # z-score 3이상인 것들 없애기
    z_score = np.abs((df["TotalCharges"] - df["TotalCharges"].mean()) / df["TotalCharges"].std())
    df = df[z_score < 3]

    # IQR 이상치 제거 [Age]
    Q1 = df["Age"].quantile(0.25)
    Q3 = df["Age"].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df["Age"] >= lower_bound) & (df["Age"] <= upper_bound)]

    # 인덱스 재정의
    df.reset_index(inplace=True, drop=True)

    # 나이를 정수형태로
    df["Age"] = df["Age"].astype("int")

    # 성별을 소문자로
    df["Gender"] = df["Gender"].str.lower()
    # output data : 반환(return) -> 전처리가 완료된 데이터 프레임 반환
    return df

clean_ecommerce_data()

,CustomerID,Age,Gender,Tenure,MonthlyCharges,TotalCharges,SupportCalls,ReviewScore,Churn
0,4,32,male,3,44.06,13888.00,4,4.6,1
1,10,40,female,15,36.90,50671.00,1,2.2,0
2,11,28,female,16,22.14,36716.00,5,1.2,1
3,22,47,male,54,117.37,6880.05,5,1.8,0
4,23,55,male,27,68.26,1736.67,0,2.3,0
...,...,...,...,...,...,...,...,...,...
4977,4996,24,male,17,131.19,2441.28,7,1.8,0
4978,4997,66,female,5,31.12,164.20,2,1.3,1
4979,4998,26,female,18,11.80,199.44,4,3.5,0
4980,4999,53,female,55,25.40,1455.62,5,2.6,0
4981,5000,36,female,53,60.91,2953.91,0,1.7,0

In [18]:
len(clean_ecommerce_data())

4982