## [실습] 주택가격예측 데이터셋 이용

In [2]:
"""
KNN, LinearRegression 모델 이용..
"""

'\nKNN, LinearRegression 모델 이용..\n'

In [3]:
# 숫자 처리
import numpy as np

# 데이터 처리
import pandas as pd

# 훈련:검증:테스트 데이터 분리 처리
from sklearn.model_selection import train_test_split

# 훈련모델
# 선형회귀 모델
from sklearn.linear_model import LinearRegression
# KNN 모델
from sklearn.neighbors import KNeighborsRegressor
# 특성 늘리는 클래스
from sklearn.preprocessing import PolynomialFeatures

# 표준화 데이터 스케일링
from sklearn.preprocessing import StandardScaler

# 오차확인(테스트 오차)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df = pd.read_csv("./dataset/01_회귀_주택가격예측_데이터셋_Row_1000.csv")
df.info()
df.describe()
df.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   면적          1000 non-null   float64
 1   층수          1000 non-null   int64
 2   역까지_도보시간    1000 non-null   float64
 3   주변_편의시설_점수  1000 non-null   float64
 4   주택_가격       1000 non-null   float64
dtypes: float64(4), int64(1)
memory usage: 39.2 KB

           면적  층수   역까지_도보시간  주변_편의시설_점수         주택_가격
0  121.146284  13  35.025575    9.100563  16601.167450
1   69.040391  27  21.442580    2.792623  11420.654974
2  153.858939   8  10.174919    2.803478  23286.484864

In [5]:
# 독립변수(X) : 면적, 층수, 역까지_도보시간, 주변_편의시설_점수
# 종속변수(y) : 주택_가격

In [6]:
df_c = df.copy()
df_x = df_c.drop(columns=["주택_가격"], axis=1)
df_x.info()
df_y = df_c["주택_가격"]
df_y.info()
train_X, test_X, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=42)
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   면적          1000 non-null   float64
 1   층수          1000 non-null   int64
 2   역까지_도보시간    1000 non-null   float64
 3   주변_편의시설_점수  1000 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 31.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: 주택_가격
Non-Null Count  Dtype
--------------  -----
1000 non-null   float64
dtypes: float64(1)
memory usage: 7.9 KB
(700, 4) (700,)
(300, 4) (300,)

In [7]:
# 데이터 분리하기 7:3

train_X, test_X, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=42)
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(700, 4) (700,)
(300, 4) (300,)

In [8]:
knr = KNeighborsRegressor()
knr

# 훈련시키기
knr.fit(train_X, train_y)

# 정확도()
train_score = knr.score(train_X, train_y)
test_score = knr.score(test_X, test_y)
gap = train_score - test_score
print(train_score, test_score, gap)

# 예측
pred_train = knr.predict(train_X)
pred_test = knr.predict(test_X)
print(pred_train)
print(pred_test)

0.995540158253338 0.992629312248022 0.0029108460053159924
[ 9650.74108504  9210.9982556  29846.8059026   6702.51585275
 20148.25960678 14644.09484634 35575.87277392 10405.20858823
 12870.65836785 13136.8324206  37412.75883547  6029.19929332
 26500.03174381 12464.84798453  6985.12087367 12870.65836785
 23957.00610244 20905.53981738  7402.33870604 30360.1524854
 10016.21308379 19516.9676927  34509.52713231 11892.4124573
 22182.35842735 37739.76323767 28762.71568443 19643.05441053
 23465.73546107 22235.62612537 18724.1350872   9365.62420701
 30632.80751345 22564.68676944 16880.90806005 13687.17900765
  9201.87044452  9789.9275945  35209.21517236 13081.56818861
 10707.92265828 19013.54212675 22196.70077168 38676.73411475
 29807.8653114   3679.46767479 10411.46749257  9707.22428049
  4729.31876491 25887.36589915  9154.66638324 10190.06854725
  9203.05439847  8004.85398339 38450.467552   18746.74962732
  7807.2992041  33579.11322805 12638.29225012  7133.70130961
  8220.96753839 25034.8299625   9249.97256795 18624.50757985
 21323.4309105  33426.44766945 23692.88273979 30629.52169535
 14902.99517147 14172.41466612 19908.32111441 15324.36973411
 36809.0748234  11430.66347362 30227.99159259 13531.95921582
 14907.40110511 40413.92074957 22574.98778061 11769.28022495
 21231.32742886 12523.12695312 13531.95921582  9447.94872414
 18120.12123024 31573.86463387 35841.50063298  8461.43098974
 25541.47120006  9537.232628   39403.62358298 13626.94015941
 12582.9657552  12550.95088412 16510.81651492  9688.71953535
 18291.23340096 21877.84976361 13124.93578177 11497.44967994
 20065.2549951  19685.46827013  9425.16470297 39514.41480069
 15327.27643832 10893.78093286  9415.2417456  25391.15047827
 21449.81199263 35036.27016142  3631.52845719 29856.80571902
 10429.37772153 23928.74463797  7018.14814531  7618.7608302
  3284.03650683 24396.25667543  6643.33968751  8865.79950199
  3505.03816268 24018.14338887 13721.8807854   9560.19483696
  9986.03376874  5481.70446655 26500.03174381 20833.19104518
 13723.42567021  3601.74853565 16496.69849712 11087.40959597
  8128.08116926 15397.7756121   9078.31091765  9160.72625757
  9956.16663792  9726.449678   36974.98051168  9401.65186657
 33811.48645922 13285.32133136  9918.47784009 33866.72238682
  5452.70076346 35820.72626615 38127.49976763 37394.27228074
  6500.14879015 23267.10770914 38965.66584985 29846.8059026
 11615.8618037  28564.01515666 11033.83417176 12468.31326457
 39366.12275357 11500.60140386 35057.3786937  34754.76156906
  2790.21407325 36929.4341072   8548.18127808 16171.13711024
  8027.29300927 28359.36678126 12752.38005424  5304.84070477
 14659.46573794 36595.12418838 19919.97167067 34042.97039818
 18352.70762392 40440.72066266 13882.47023798 24013.20304121
 23411.43958804 39591.28950115  7443.70716847 22234.85969294
 11062.5861695  18671.22423164 21934.94776872 38079.01874255
 21463.58570511 14197.03613225 14132.99236678 15415.54212696
 24924.76699531 29807.8653114  30098.41653739 33274.16465545
  6594.37902662 38064.9883941  32237.96290125 15324.36973411
  6774.93196268  6693.68365253 14421.74863086 13271.66825914
  6496.15632604  5373.33023294  8799.5973274   8474.76830205
 28243.87601993 20086.23405223 24441.64234332 22974.1609462
  3774.35142076  6311.22571002 10515.50903137 23696.96169618
  4891.96914836 36251.74303136 19892.45311704 37067.35093251
 34780.52750507  5806.18078086 28384.55478231 14561.63007676
 14371.82574272 19153.72923156 13944.18435298  7967.10640167
  8811.84658603  8633.5146498   6606.38637437  9365.62420701
  4308.307646   37189.50543429 30255.79596917 14922.72863555
 29137.52596047 13531.95921582 34466.44074079 18732.7240565
  7888.5930621  39039.34683252 19594.06762249 33623.81785958
 38073.77751791  9690.48848343 28305.42605359 12465.72965022
 31414.10675261 12030.38060693 29578.73585269 12590.2716281
 15324.36973411 36708.23294074 16226.67542213 32806.73349847
  8243.68123718 13798.11789613 11033.83417176 27570.61275766
  7655.63320405 11206.87158212 17819.29885976  6692.4934959
 12041.2035501  14357.13068921 14157.75849066 23073.5691177
 37308.69470957  5201.53244749 23848.57404803 20601.60665515
 32806.73349847 38073.77751791  5769.26255966 24348.18716332
 19013.54212675 13319.91970433  9849.22585394 17381.61177222
  9872.40817625 18352.78580528 20112.98957008 34002.95029883
 24777.21130293 27351.64433696  6692.4934959   7992.92748819
 10030.49341848  4393.90360473 30462.87261883 21842.14055666
  6029.19929332  3554.83881614 38094.63258912  3505.03816268
  3515.3418527  10083.43049654 29693.04938292  4517.37309914
  9311.54236081 26043.04916188 29561.84289505 28837.30785731
 29263.65803318 28696.93668895  9420.87080027 40488.44512608
 21831.95027827 38267.93886557  5574.15679212 24974.59033889
 32435.26202215  4308.307646   32735.41347251  8671.5849379
  8142.935714   29730.0407009  15169.65607229 14348.19601735
  6774.93196268 10342.518772   33811.48645922 26414.39344299
 23244.04637513 36219.11752743 27496.52461641 11663.34130525
  9026.54304166  8186.43927033 32178.59488261 26765.63439054
 10474.60278013  7655.63320405 18207.90705622 35620.15152412
  9252.48605871 13298.31879412 10020.62699991  4933.04237126
 15886.75541963 25233.19477392 14288.16682678 22662.50873675
  6242.64255861 10370.97370158  8921.683774   19763.87047889
  8448.4509342  12422.72446295 15963.30686614 22442.24772587
 15971.63115395 19866.92653465 16880.53427832  8714.6730088
 32436.9072685  29494.13244262 19445.31625897 21764.76004294
 26134.57037799  5620.17219069 22554.10089106 10865.35373061
  5502.93513233 13298.31879412 14683.60767312  7173.279973
  6702.51585275 29089.29054314  7351.64161949 10327.17741893
 12389.59199396  3554.83881614 10543.59419458 18851.87563321
 35036.27016142 40716.25952376 10669.30179248 17808.38328391
 11572.31754699 23516.9280233  16918.61064298 23290.20268466
 38029.41100182 17924.55635847  4881.78542662 24862.41915524
  8646.65590692  4308.307646   24396.25667543 33426.44766945
 30712.88088987 38848.20576381 22760.89643345 28899.4446505
 22184.64126371  9510.41542676 24441.64234332  4988.44675673
 11477.04072111 21504.28234019 22985.79192352 22526.65110663
  6821.46711638  6821.46711638 12630.72093144 12465.72965022
 40348.18919411 24880.29130677 13085.55090108 20276.46659707
 27497.08073287 30059.56325371 13517.89507545 24989.31288453
 10231.94773722 16310.3902868   9835.61112337 38029.41100182
 28577.1057732  22373.88744221 17272.76478822  5249.294923
 24386.0671858  36622.16849454 33124.43277106 25314.35239826
 15293.69361671 33638.09448129 20065.2549951  16303.37450594
  8210.71839716 21223.66753077  7769.68170942 31316.09806589
 16918.16728922 13804.76002597  5214.49479739 31390.18880171
 11602.0817878  23409.73364601 14843.6525338  30288.330986
 20777.16247154 36736.19299145  4519.87229138 11155.85512879
 31531.70270372 28170.12314555 38835.20235388 35401.94397753
 36708.23294074 19922.88167059  5102.64895165 22014.71091279
 17123.20406476 10870.93172764 30155.94740392 22234.85969294
  7854.38135752 17027.4271173  20822.18541147 12733.63224161
  5771.18018468 27781.40591275 28602.98960906 36907.64567616
 19047.15912275  6456.3389184  24743.83304152 20086.23405223
 21315.31737223  9425.16470297 12744.2751213  36801.00223752
 14255.17063129 23779.94350964 35742.863873   31531.70270372
 16192.77281401 16417.35520112 10682.37733707 22289.00110477
  9942.59940189 13298.31879412 18174.84430205 15963.30686614
 11769.28022495 18016.04456921 17683.01345951 28891.44213389
  8128.08116926 15324.36973411  8022.52476542 17604.37495504
 21063.48713966 21892.55918598 28794.82430903 37308.69470957
 26500.03174381 28895.18768905  5102.64895165 19277.13537679
 14256.63538526 38231.35198667 29976.40332311 13613.96472869
 19214.23218523 19710.60393032 16042.76733129  9951.33641467
  8663.15350847  2811.12449535  8027.29300927  9308.27520234
 29958.53043789 20051.57576288 15747.2523074   7842.50867759
 22209.48629775 17603.70859635 13730.8542428   9365.62420701
 37625.43994952  7515.96823881  7127.06632721 38361.00178149
 14206.56669283 33426.44766945 21387.4676828  39591.28950115
 14897.28478513 22526.65110663 10082.82680564 34311.00627972
 31383.50546317 11671.72887847 30442.41743978 12416.67655504
 23776.28581115  7854.38135752 14907.40110511  4699.64523813
  8094.0449535  18174.84430205  9814.52707077  6566.53887506
 16420.37185136  2941.35856429  9835.61112337 10492.58061632
 26757.53684729 14433.26019082 32806.73349847  6004.4468916
 20005.36015974  7677.96900953 21118.05359242 12681.24071141
 30671.59566491 24499.80774418 10825.57843799 34966.28860796
 23345.87130553 12113.86889469 18269.3964466  23107.99385732
 19153.72923156 15430.45852069 22489.95992099 19908.32111441
 15639.01930536 21804.64877027  7648.27212141  8342.52820908
 22184.64126371  4800.91637141 13298.31879412  8397.4138791
 18291.23340096 38094.63258912 22671.48657544 35036.27016142
 23280.26328908  7874.24380824 10020.62699991  6221.75695021
 34121.28850826 27896.8494951  30669.02862361  3394.0763219
 15022.21853413  7216.32142398 29673.5047948   4627.88394135
 36588.57593142 14211.34635988 30209.01260728  5102.64895165
  7964.0216844  33690.19702019 24240.48224633  5817.92506875
 10889.22473976 10747.06030363 12434.51433546 24441.64234332
 24905.40253165 35620.15152412 30120.60450761  6165.46905696
 34948.36986814  5872.68906952  5719.98968254 19584.94415193
 37121.30396812  4949.47545468 31851.94339147 12092.13540317
 29545.49516055  9986.03376874  5719.98968254 10100.07993575
 21696.1425873  30632.80751345  8012.37183228  5440.91926248
  9804.46138353 19349.04816099 22235.62612537 34679.04212046
  7992.92748819 19232.29550902  5181.88499822  7715.21319537
  5681.50691073 37879.49861515  5456.51497192 37892.59667291
  5468.17513377 11670.73692123 36673.56802136 13298.31879412
  5654.86786204 37781.01850168 21174.43181347  6483.77541358
 22365.34243631 25821.53088464 29701.33492254 12543.43558511
 15416.39877399  8638.78792056 17511.7338641   7851.2666653
 23198.27482439  7851.2666653  13563.11193009  7759.8676932
 14268.6385458  21935.64069128 22050.34866729 11587.36161549
 16510.81651492 19231.07157612 20305.10085266 21063.48713966
 17561.07956037 36454.98947246  8233.57853765  9826.01289527
 26743.32749505 25732.96862768 17457.21119748 20051.57576288
 25798.97437737 28115.86360628 22435.66124674  8215.76532299
 13379.66210384 13613.96472869 13189.76722179 13989.40797004
  8991.49508288 21360.37628804  7977.95018065 13829.06492988
  4508.85293814  9858.54322973  9890.72030696 22526.65110663
 22633.39245408  6606.38637437 38361.00178149 14634.7604058
 13531.95921582  3508.34470974 24574.9548667  37217.96727479
 21764.76004294 10294.11099009 24900.98468042 31531.70270372]
[37254.29234465  4660.40275584 22257.80265324 27291.01454644
 23162.75872686  6244.71752568  4933.04237126 27036.04386555
  5214.49479739  8334.74639215  6938.24409302 27970.2001875
 10990.07873906  3935.94535793  5514.55431871  5377.49306652
 13504.21941634 15216.06744017  7992.92748819 14132.99236678
  7907.24865303  5876.94269102  3270.20184223  6016.02030219
  3818.35501236  4627.88394135 37879.49861515  7429.83581207
 26219.9040938  11552.54507841 21764.76004294  3518.01444833
 11430.66347362  4938.94731701 13181.76617338  8448.4509342
 38361.00178149 19339.02806429 33610.96024658 34290.57319775
  5343.20060795 22294.30692053 11064.0198806  33459.49393481
 25844.68439108 38691.04977029 15949.68025343 18322.99969199
  9792.18890557 29499.18633507  7957.69732941 17201.38230808
 14000.79762323  7823.53855227  8834.19010995 29308.50813829
 13733.54606449 16310.3902868  13313.76606775 14681.68470886
  8077.7195028  21091.97576463  5876.94269102 12750.04506412
 18904.01559734 24036.94411155  8732.0824973   9987.79721226
  3710.3525152   9367.54852048  9866.72645323 15186.4019232
 29015.16726008  7533.84790484 16680.87411131  4320.73903795
 21738.95045187 13834.87783119 10227.96739361 39040.5858428
 39514.41480069 19536.58176027 29932.11889257 28941.01501239
 19836.74178975 12422.72446295 21207.52492697  9852.60430956
 13394.96302275 32436.9072685   5445.00201989 28551.86677522
  9068.91513643 22436.88662366 13416.47934834 20003.18608496
 13718.48396326 11094.24659005 23745.40914564 31632.48883802
  8510.84983279 14511.71779067 41427.56445151 11638.58000883
 12111.30847968  3924.38548903 20675.55835286  8511.70011264
  3211.97627329  9104.66395294 34510.15257282 31955.81789973
 32572.30233851  7665.27384638  9614.77272847  8120.54695119
 16396.98940461 14043.53720461  8215.76532299 16515.06853534
 11892.4124573  27722.44052548 22099.70226719  9455.03359329
 16560.98263479 38196.1613765  15539.51206554 38331.35110704
 36251.74303136 15352.61986807 21994.02678498 26317.80046168
  9063.91355318 12982.78287712 35057.3786937  16149.95504978
  5249.294923   36907.64567616  4099.29034611 30028.99388159
  9427.37084699 20460.3543952  32067.68512437  4381.40237672
 21908.82443311 11158.81814655 30302.74342837  5114.09436424
  2811.12449535  4456.43142724 32376.70877501 22382.64163935
 34501.19419909 12955.13717659 21055.09389434  2690.97396633
 10870.93172764 11039.76827264 37728.18110982 30149.61506085
 31151.17032909 18205.22545601 23251.04970648 13177.26258643
  9174.640253    7999.16315785 25889.22456778 38723.39940413
 20088.89145269 21224.62952166 33325.58927923 33043.11197844
  3373.7270264  29265.56796629 12150.54250847 23149.97624605
 20054.39682294  7632.23574956 23335.11795931 10423.84571922
 15825.95649487 29954.54926733  8304.45035039 23305.8000377
  7287.72384914 26568.47364614 30099.07965892 13340.5230455
 27622.29855999 28790.37512834 13360.8123785  14907.40110511
 33866.72238682  6866.48958772 28838.19802079  7926.32799314
 12104.71451537 39543.1623129  34068.41714605 14172.37852864
 24449.11511607  3529.21642629 22750.13814614  6983.71459848
 37308.69470957 20489.04340355 10525.70312274 28170.12314555
  3284.03650683 14181.93536161 38235.47438915 29824.94997769
 30783.3711448  39040.5858428  21553.78248301 15454.35671679
  4575.86247412 21893.97043372  5905.30308154 12551.9309678
 10979.57465394 11254.39843251 38069.84476073 34144.10832487
 16510.81651492 23776.28581115  6646.68022694 26677.13080782
 23073.70547486 21022.51834634 27036.04386555 16577.06206788
 26736.33601214  6485.41060232  6092.84987009 23952.38890704
 40488.44512608 24407.53017359 22268.9932242  14664.84078163
  8466.51228425 24271.21477414 20690.01582144 12771.50777659
 10020.62699991  6370.57801855 12180.51534108 13344.9921037
 28205.36302619 28409.18884272  9620.175912   11510.5771435
 14531.4988727  11943.88852072 35622.15686341 14576.60746441
 33459.49393481  9679.5036482  24652.79251015  7181.36422078
 19539.47920051  5087.78289453 29172.20925146  4537.79358816
 29566.71651685  8194.25458489 38353.42964247 33434.78317182
 12328.83431587  9210.9982556   9746.12282243 24711.41521266
 33525.39972589 20221.7912663  20161.91529345 10207.60222442
 29716.05074348 33866.72238682  3508.34470974 21008.71234457
 33650.75555158 21554.1721952  15048.04062391  5311.81137431
 13404.5271501  25383.53520859  4773.80468929  9826.01289527
 11792.94677119 26490.30414814  8035.94395272 18625.44533907
 21519.43538719 27638.4643398  11735.46969013 18897.0968439
  6554.96693716 11386.28069702 29846.8059026   6294.22869674]

In [9]:
# 클래스 생성
lr = LinearRegression()
lr

# 훈련시키기
lr.fit(train_X, train_y)

# 정확도()
train_score = lr.score(train_X, train_y)
test_score = lr.score(test_X, test_y)
gap = train_score - test_score
print(train_score, test_score, gap)

# 예측
pred_train = lr.predict(train_X)
pred_test = lr.predict(test_X)
print(pred_train)
print(pred_test)

0.9667666579420744 0.9686673480370794 -0.001900690095005042
[ 7.87596009e+03  9.18074423e+03  3.04559530e+04  6.76103905e+03
  2.15651390e+04  1.56218834e+04  3.34709478e+04  1.10144698e+04
  1.56390901e+04  1.47661454e+04  3.55752886e+04  4.91981232e+03
  2.62039454e+04  1.34775188e+04  8.16182338e+03  1.41505673e+04
  2.50689064e+04  2.27645221e+04  6.38167900e+03  2.74047430e+04
  7.80456119e+03  2.09931221e+04  3.25879985e+04  1.29076430e+04
  2.35549010e+04  3.49496755e+04  2.89930596e+04  2.19681207e+04
  2.53893967e+04  2.16594599e+04  1.95813907e+04  7.05057751e+03
  2.89155779e+04  2.45924571e+04  1.87146676e+04  1.55384410e+04
  1.10409787e+04  5.95759019e+03  3.16341593e+04  1.41864903e+04
  1.14752551e+04  2.06669186e+04  2.38565307e+04  3.58424387e+04
  2.76905597e+04  2.93973960e+03  1.00909515e+04  1.03837974e+04
  2.34244122e+03  2.80042468e+04  7.71738758e+03  1.15997917e+04
  1.00382958e+04  1.03267777e+04  3.68727603e+04  2.04500482e+04
  7.91606893e+03  3.26124487e+04  1.39191179e+04  3.96637939e+03
  7.12476784e+03  2.70145483e+04  9.73008349e+03  2.02147631e+04
  2.35527674e+04  3.16075600e+04  2.55377073e+04  3.07327566e+04
  1.64436809e+04  1.67585905e+04  2.15298382e+04  1.74926558e+04
  3.45523152e+04  1.23760803e+04  3.09247275e+04  1.66494140e+04
  1.77497721e+04  3.73751699e+04  2.46960895e+04  1.06734859e+04
  2.31481726e+04  1.25851595e+04  1.52525085e+04  8.88255271e+03
  2.02694736e+04  3.03276955e+04  3.18295923e+04  8.64159554e+03
  2.69586363e+04  1.13297730e+04  3.69540321e+04  1.53496896e+04
  1.39955731e+04  1.34592618e+04  1.81619997e+04  1.13973570e+04
  2.04799733e+04  2.27455852e+04  1.50584511e+04  1.19728995e+04
  2.06726996e+04  2.12055482e+04  1.03935450e+04  3.79242556e+04
  1.66622573e+04  1.16740485e+04  5.95286999e+03  2.70212845e+04
  2.26516783e+04  3.34316316e+04  9.54057219e+02  2.86720350e+04
  1.29414731e+04  2.56895685e+04  6.05358943e+03  5.57136899e+03
  3.46945340e+02  2.62421459e+04  6.51831621e+03  9.44899809e+03
  2.35268883e+03  2.55581050e+04  1.50797204e+04  8.84679220e+03
  9.60199656e+03  3.13662780e+03  2.68573483e+04  2.28015025e+04
  1.50066642e+04 -4.95739321e+02  1.86806137e+04  1.34006503e+04
  7.51482938e+03  1.72921188e+04  1.01727519e+04  9.89228888e+03
  8.99800156e+03  9.86008490e+03  3.43122651e+04  1.10434549e+04
  3.37689617e+04  1.29413825e+04  1.02638374e+04  2.90178163e+04
  2.23449836e+03  3.27210258e+04  3.55826905e+04  3.46205865e+04
  5.39892904e+03  2.58045818e+04  3.59298146e+04  3.01551244e+04
  1.25313860e+04  2.85411414e+04  1.09265679e+04  1.45549694e+04
  3.77779958e+04  1.02832658e+04  3.39406395e+04  3.33641286e+04
 -1.49064697e+03  3.60955204e+04  7.58649683e+03  1.64131524e+04
  8.49173349e+03  2.97160902e+04  1.42832898e+04  3.50522438e+03
  1.85228217e+04  3.21700780e+04  2.31538968e+04  3.15546250e+04
  1.99680731e+04  3.71981630e+04  1.56580497e+04  2.51429601e+04
  2.45964041e+04  3.63704802e+04  7.06338402e+03  2.51527200e+04
  1.19167442e+04  2.08402432e+04  2.40716178e+04  3.55483666e+04
  2.40666484e+04  1.66656704e+04  1.60429655e+04  1.69626056e+04
  2.70291520e+04  2.80676106e+04  2.83889584e+04  3.28373792e+04
  4.74489495e+03  3.60277770e+04  3.07029898e+04  1.87085422e+04
  2.71587199e+03  3.35354464e+03  1.52502555e+04  1.41811182e+04
  3.96541266e+03  1.84403395e+03  8.49041639e+03  9.32391013e+03
  2.90364651e+04  2.33240298e+04  2.53680789e+04  2.44861539e+04
  6.40280450e+02  3.32207991e+03  1.22087732e+04  2.54246346e+04
  1.15565594e+02  3.52575700e+04  2.22791068e+04  3.50227129e+04
  3.34368957e+04  4.27828727e+03  2.80821625e+04  1.76824935e+04
  1.67945591e+04  2.08396409e+04  1.54741517e+04  7.89535530e+03
  8.71384896e+03  9.29228293e+03  4.34132022e+03  7.45277862e+03
  8.67376900e+02  3.42550791e+04  2.89803337e+04  1.59962283e+04
  2.68019314e+04  1.58662796e+04  3.18133722e+04  1.98425313e+04
  8.40926447e+03  3.60321291e+04  2.13201979e+04  3.27378409e+04
  3.49911430e+04  1.10674726e+04  2.81260585e+04  1.54304347e+04
  2.99389637e+04  1.18979147e+04  2.90960045e+04  1.23305986e+04
  1.66123018e+04  3.53525169e+04  1.67152139e+04  3.09120720e+04
  8.70701092e+03  1.51695733e+04  1.16442627e+04  2.72442059e+04
  8.37942435e+03  8.77524100e+03  1.88427086e+04  6.23562191e+03
  1.39790540e+04  1.67726153e+04  1.51613305e+04  2.41045942e+04
  3.35875953e+04  2.31413638e+03  2.32247418e+04  2.32537460e+04
  3.02434126e+04  3.48513393e+04  4.46008175e+03  2.43852156e+04
  2.10526502e+04  1.44050417e+04  1.06480729e+04  1.79516868e+04
  7.24601579e+03  2.00019602e+04  2.24717851e+04  3.30697348e+04
  2.59490022e+04  2.88891432e+04  6.56370774e+03  8.08452866e+03
  6.78203116e+03  9.21045851e+02  3.11279702e+04  2.42731353e+04
  5.34928138e+03  3.42799988e+03  3.51990210e+04  2.55295956e+03
 -6.45455421e+02  1.14686889e+04  2.70934702e+04  1.03482107e+03
  7.20694320e+03  2.61488891e+04  2.84251758e+04  2.89117936e+04
  2.94955020e+04  2.82657150e+04  1.11646651e+04  3.80497826e+04
  2.32171464e+04  3.48655358e+04  4.81997385e+03  2.56399275e+04
  3.34869813e+04 -1.35658194e+02  3.08615135e+04  7.89349229e+03
  1.08171092e+04  3.11474697e+04  1.79678990e+04  1.61797259e+04
  3.45471115e+03  1.02964281e+04  3.27609453e+04  2.55849202e+04
  2.59213439e+04  3.32699824e+04  2.80103361e+04  1.24710645e+04
  6.94051384e+03  4.44695031e+03  3.04169263e+04  2.77283309e+04
  1.34410029e+04  7.83661486e+03  1.95963222e+04  3.35141670e+04
  9.93486471e+03  1.56132878e+04  9.48421784e+03  1.01375619e+03
  1.85776920e+04  2.43393954e+04  1.44992810e+04  2.51181913e+04
  5.42778651e+03  1.10794632e+04  1.01625511e+04  2.14812013e+04
  6.44408234e+03  1.37097264e+04  1.95627905e+04  2.27550085e+04
  1.69796672e+04  2.03131402e+04  1.90366473e+04  8.48077857e+03
  3.17234956e+04  2.77467633e+04  2.00007807e+04  2.17709868e+04
  2.49488002e+04  2.18144519e+03  2.56586754e+04  1.14735826e+04
  3.44079534e+03  1.56670169e+04  1.62628101e+04  3.75003104e+03
  6.37336709e+03  3.04486009e+04  7.12475546e+03  1.23644406e+04
  1.26850622e+04  1.87832764e+03  1.14589213e+04  2.05356626e+04
  3.20781537e+04  3.97485427e+04  1.13720160e+04  2.13689134e+04
  1.24495618e+04  2.48687970e+04  1.74551808e+04  2.42791178e+04
  3.56026185e+04  1.93012996e+04  2.74678986e+03  2.63887746e+04
  5.52924046e+03  5.16787927e+02  2.56911674e+04  3.31619813e+04
  2.99137614e+04  3.52939269e+04  2.42290742e+04  2.82018463e+04
  2.29012211e+04  8.67840750e+03  2.48346599e+04  1.25751426e+03
  1.25594602e+04  2.35428618e+04  2.29420729e+04  2.35835700e+04
  5.11300313e+03  5.50095734e+03  1.26570488e+04  1.55994148e+04
  3.85451413e+04  2.62897546e+04  1.38925165e+04  2.25943137e+04
  2.79655420e+04  3.07128044e+04  1.56605855e+04  2.53970806e+04
  1.19858959e+04  1.79095505e+04  1.12102380e+04  3.39349269e+04
  2.90528469e+04  2.36389429e+04  1.87399821e+04  3.87273325e+03
  2.58600065e+04  3.34839622e+04  3.15758902e+04  2.64009117e+04
  1.81316934e+04  3.15643528e+04  2.09396164e+04  1.87636699e+04
  5.63756402e+03  2.35479345e+04  6.82246717e+03  3.15736852e+04
  1.99679960e+04  1.54386483e+04  5.13303048e+03  3.06168522e+04
  1.24129082e+04  2.54423716e+04  1.73282879e+04  2.95514299e+04
  2.29167887e+04  3.27176962e+04  5.93381789e+02  9.97381709e+03
  3.12245693e+04  2.80504150e+04  3.60783230e+04  3.13225037e+04
  3.44831891e+04  2.16622799e+04  4.04530573e+03  2.39295561e+04
  1.85450700e+04  1.19007194e+04  3.07128815e+04  2.41810681e+04
  7.16623357e+03  1.69186360e+04  2.32131499e+04  1.43398657e+04
  4.31105216e+03  2.85619395e+04  2.80828847e+04  3.34573669e+04
  2.09370162e+04  7.52524866e+03  2.43267123e+04  2.27115630e+04
  2.33638715e+04  1.03683161e+04  1.43528480e+04  3.34495558e+04
  1.55451473e+04  2.40977538e+04  3.38596909e+04  3.11748781e+04
  1.70256694e+04  1.74717165e+04  1.04399581e+04  2.26199289e+04
  1.21408269e+04  1.54220324e+04  1.96321451e+04  1.88650038e+04
  1.01175045e+04  1.84819559e+04  2.00467768e+04  2.63573353e+04
  7.88743544e+03  1.93983553e+04  9.34236266e+03  1.93374798e+04
  2.27527555e+04  2.37968079e+04  2.97600489e+04  3.32221059e+04
  2.60361041e+04  2.93545490e+04  6.24570842e+03  2.13688177e+04
  1.60501427e+04  3.57533567e+04  3.00422602e+04  1.36359883e+04
  2.14316689e+04  2.09932083e+04  1.88670270e+04  1.34100345e+04
  8.73271738e+03 -8.70654849e+02  7.17042138e+03  1.00376826e+04
  3.07709018e+04  2.25910365e+04  1.76665071e+04  7.29186409e+03
  2.37162640e+04  1.92645549e+04  1.53683383e+04  6.01953359e+03
  3.44442315e+04  6.44657742e+03  5.48807240e+03  3.71000174e+04
  1.48655049e+04  3.09343820e+04  2.44212108e+04  3.62118600e+04
  1.76310569e+04  2.40239313e+04  1.19112238e+04  3.28296907e+04
  3.11244533e+04  1.31921346e+04  2.91356906e+04  1.34333205e+04
  2.51761262e+04  6.45509627e+03  1.78800481e+04  1.56889504e+03
  8.47326285e+03  2.10639357e+04  1.10810923e+04  4.27968869e+03
  1.71469396e+04  8.24436896e+00  1.08919550e+04  1.31595351e+04
  2.73238629e+04  1.55819930e+04  3.01678587e+04  1.94458621e+03
  2.17588468e+04  7.54625465e+03  2.06728529e+04  1.40687135e+04
  3.05562189e+04  2.52459770e+04  1.18270246e+04  3.22443501e+04
  2.48603822e+04  1.26351091e+04  2.09926202e+04  2.43848035e+04
  2.03791046e+04  1.85482045e+04  2.41980834e+04  2.24235137e+04
  1.80924094e+04  2.33444206e+04  6.55598368e+03  9.22489367e+03
  2.37735835e+04  3.40640473e+03  1.52833377e+04  8.17023903e+03
  2.11795238e+04  3.64138260e+04  2.29773476e+04  3.26867748e+04
  2.62335501e+04  8.16527915e+03  1.00541672e+04  3.90571107e+03
  3.25656514e+04  2.86322010e+04  2.92403823e+04  1.69183143e+03
  1.70572947e+04  6.31952220e+03  3.19717778e+04  1.92249826e+03
  3.24657727e+04  1.51797919e+04  3.06116628e+04  6.27077839e+03
  7.95805800e+03  3.24391655e+04  2.49515219e+04  2.50915201e+03
  1.18804218e+04  1.07284631e+04  1.19435313e+04  2.65078132e+04
  2.58890180e+04  3.37002489e+04  3.00498998e+04  3.57129508e+03
  3.42255791e+04  2.79811830e+03  2.59266732e+03  2.25631672e+04
  3.28734087e+04  1.58589354e+03  3.18265547e+04  1.06592987e+04
  2.90963819e+04  9.78010011e+03  3.52472949e+03  1.15843917e+04
  2.24406640e+04  3.04558655e+04  7.78412742e+03  1.18029192e+03
  5.86824137e+03  2.14775867e+04  2.21936526e+04  3.35248134e+04
  8.96785607e+03  2.19327290e+04  3.15220444e+03  7.75459720e+03
  2.93586003e+03  3.56373651e+04  3.61842914e+03  3.61444300e+04
  5.50927511e+03  1.06717399e+04  3.54632861e+04  1.38366452e+04
  2.75876945e+03  3.44811143e+04  2.26429959e+04  5.74521854e+03
  2.31125779e+04  2.72974060e+04  3.06346481e+04  1.50072971e+04
  1.76449300e+04  6.18919873e+03  2.01251892e+04  8.54397053e+03
  2.46002418e+04  6.43302151e+03  1.65132539e+04  8.68016755e+03
  1.57174666e+04  2.46811908e+04  2.35462363e+04  1.38896281e+04
  1.79897578e+04  2.04700799e+04  2.19563823e+04  2.27952727e+04
  1.90828210e+04  3.30216390e+04  6.05786463e+03  1.06062942e+04
  2.58839192e+04  2.63403256e+04  1.90348108e+04  2.23827917e+04
  2.54199594e+04  2.74974386e+04  2.52536943e+04  8.56270230e+03
  1.61330643e+04  1.43694270e+04  1.39050331e+04  1.52865297e+04
  8.41194251e+03  2.24754906e+04  8.88716790e+03  1.65953165e+04
  7.93516905e+02  7.19373607e+03  7.75380566e+03  2.49160158e+04
  2.55115691e+04  5.38157357e+03  3.72067654e+04  1.77085150e+04
  1.62857691e+04  1.97759556e+03  2.56048098e+04  3.47834629e+04
  2.35086614e+04  1.10715074e+04  2.62178626e+04  3.15646494e+04]
[ 3.52567436e+04  2.60750036e+03  2.42395876e+04  2.92755337e+04
  2.57842328e+04  5.87056019e+03  3.31916850e+02  2.75125308e+04
  5.84065789e+03  5.39968821e+03  6.82355735e+03  2.81668977e+04
  1.24701839e+04  3.58424628e+03  3.28034461e+03  1.93400828e+03
  1.38500045e+04  1.71536815e+04  8.48584368e+03  1.61364484e+04
  5.29650715e+03  3.47998400e+03  3.15910069e+02  2.37666844e+03
  4.28515649e+03  2.87220304e+03  3.48099451e+04  4.07913381e+03
  2.81218824e+04  9.86135404e+03  2.36690314e+04  1.60828282e+03
  1.33297138e+04  4.20104063e+03  1.58423087e+04  6.42405282e+03
  3.65895813e+04  2.06140201e+04  3.17987183e+04  3.24278448e+04
  3.01986410e+03  2.22275526e+04  1.30330149e+04  3.27663490e+04
  2.69705369e+04  3.53741092e+04  1.77066612e+04  1.95112139e+04
  1.00274067e+04  2.99921549e+04  9.45280188e+03  1.92353861e+04
  1.80249698e+04  8.70558724e+03  8.22339177e+03  2.90135351e+04
  1.50349530e+04  1.73854321e+04  1.59693824e+04  1.59179541e+04
  7.16885588e+03  2.31311344e+04  3.37503505e+03  1.34823974e+04
  2.11969525e+04  2.55985940e+04  9.12309464e+03  9.98342014e+03
  1.68524714e+03  9.99082634e+03  9.65889853e+03  1.79543014e+04
  2.78199512e+04  6.10936621e+03  1.77759766e+04  8.63831145e+02
  2.14695806e+04  1.46571321e+04  1.07160528e+04  3.54378569e+04
  3.66666070e+04  2.16006317e+04  2.88203373e+04  2.83346112e+04
  2.25467893e+04  1.41727307e+04  2.26590175e+04  8.30542350e+03
  1.52959492e+04  3.13549341e+04  1.96714735e+03  2.79621728e+04
  9.07121919e+03  2.23807335e+04  1.33708399e+04  1.96691690e+04
  1.53921955e+04  1.28824122e+04  2.54228514e+04  2.89820343e+04
  8.60479551e+03  1.62610805e+04  3.97928319e+04  1.45183950e+04
  1.35162504e+04  4.08891818e+03  2.18093758e+04  7.69476000e+03
  6.56088657e+02  6.67085354e+03  3.34847238e+04  3.13783500e+04
  3.33173100e+04  6.46328023e+03  5.91041887e+03  8.20297904e+03
  1.90584960e+04  1.70484691e+04  7.49382557e+03  1.80500329e+04
  1.32747157e+04  2.79835521e+04  2.46617603e+04  1.19625455e+04
  1.84378184e+04  3.54847715e+04  1.74266962e+04  3.59252173e+04
  3.58465020e+04  1.74690140e+04  2.52668377e+04  2.64283051e+04
  6.32896765e+03  1.41647531e+04  3.27710268e+04  2.00647756e+04
  2.83697100e+03  3.45872969e+04  2.10822285e+03  2.77142961e+04
  9.54720149e+03  2.14270518e+04  3.12305246e+04  6.50217822e+02
  2.34193356e+04  1.36170150e+04  3.02700442e+04  4.87668199e+03
 -1.49040930e+03  1.11208649e+03  2.97395407e+04  2.44923300e+04
  3.41575945e+04  1.46197041e+04  2.19178607e+04  7.61092603e+02
  1.22023986e+04  1.23060446e+04  3.42008063e+04  2.92652160e+04
  3.01624762e+04  1.92749172e+04  2.79793575e+04  1.35873797e+04
  1.03382326e+04  9.54417917e+03  2.79592965e+04  3.51859175e+04
  2.23306095e+04  2.39355515e+04  3.02191363e+04  3.19783895e+04
  9.26386463e+02  2.85508213e+04  1.44513627e+04  2.59443352e+04
  2.25442792e+04  7.98096228e+03  2.63170168e+04  1.19897685e+04
  1.88618051e+04  3.19029622e+04  8.08089403e+03  2.43941465e+04
  4.88059236e+03  2.49647378e+04  3.14433421e+04  1.42687472e+04
  2.73553205e+04  2.92371144e+04  1.45696235e+04  1.80340747e+04
  2.85937415e+04  5.46786253e+03  2.88454270e+04  4.65293490e+03
  1.35355573e+04  3.79913299e+04  3.21863944e+04  1.60877095e+04
  2.54886586e+04 -3.74232378e+02  2.59021457e+04  5.35150660e+03
  3.30435388e+04  2.22110474e+04  1.12389034e+04  2.73108681e+04
  8.38090721e+00  1.71824238e+04  3.64193736e+04  3.02997600e+04
  2.97719714e+04  3.69800741e+04  2.28029747e+04  1.58433964e+04
  1.06254973e+03  2.19178423e+04  4.73155591e+03  1.38911469e+04
  1.21949782e+04  9.24053917e+03  3.48927635e+04  3.23750790e+04
  1.79916224e+04  2.44327669e+04  6.99693376e+03  2.78394133e+04
  2.30790086e+04  2.40120751e+04  2.77172683e+04  1.95249748e+04
  2.68288154e+04  3.90138893e+03  7.52547245e+03  2.49099684e+04
  3.88217897e+04  2.70932186e+04  2.45811695e+04  1.65316181e+04
  7.98148336e+03  2.30917019e+04  2.17170704e+04  1.39843233e+04
  8.46277124e+03  5.92251652e+03  1.44849124e+04  1.55283760e+04
  2.89486174e+04  2.79023855e+04  1.08486431e+04  1.21210299e+04
  1.61361955e+04  1.47733257e+04  3.38079209e+04  1.65423401e+04
  3.03770693e+04  1.01053745e+04  2.47952882e+04  3.97012191e+03
  1.98453710e+04  3.90820888e+03  2.81304567e+04  1.02232265e+03
  3.03525361e+04  7.68465987e+03  3.53838067e+04  2.96319121e+04
  1.33074663e+04  9.17945127e+03  1.07479481e+04  2.74602826e+04
  3.05059192e+04  2.19620358e+04  2.20203434e+04  9.18179812e+03
  2.93105533e+04  2.91551719e+04  1.56456366e+03  2.30249110e+04
  3.25873831e+04  2.40623446e+04  1.94796859e+04  5.26628090e+02
  1.38387713e+04  2.74322347e+04  1.92997787e+03  1.04956777e+04
  1.28196837e+04  2.74482153e+04  4.54105510e+03  2.06190577e+04
  2.44411816e+04  2.78828114e+04  1.26867920e+04  2.01751727e+04
  4.72660038e+03  1.22488274e+04  2.89998110e+04  4.68177827e+03]

In [10]:
std_scaler = StandardScaler()
std_scaler

cols = ["면적", "층수", "주변_편의시설_점수", "역까지_도보시간"]

df[[col + "_std" for col in cols]] = std_scaler.fit_transform(df[cols])
df

,면적,층수,역까지_도보시간,주변_편의시설_점수,주택_가격,면적_std,층수_std,주변_편의시설_점수_std,역까지_도보시간_std
0,121.146284,13,35.025575,9.100563,16601.167450,0.038403,-0.264641,1.330978,0.355307
1,69.040391,27,21.442580,2.792623,11420.654974,-1.021752,1.346216,-1.111780,-0.437181
2,153.858939,8,10.174919,2.803478,23286.484864,0.703980,-0.839946,-1.107577,-1.094583
3,71.656510,20,48.844439,1.983254,7535.429045,-0.968524,0.540787,-1.425210,1.161557
4,177.556747,4,2.466979,4.395939,29848.361648,1.186139,-1.300191,-0.490894,-1.544296
...,...,...,...,...,...,...,...,...,...
995,109.964997,7,47.173178,7.412281,12116.676007,-0.189093,-0.955008,0.677189,1.064049
996,37.051580,19,38.339751,7.545630,6035.386052,-1.672601,0.425726,0.728828,0.548670
997,69.009828,27,1.159038,3.559802,12017.803413,-1.022373,1.346216,-0.814689,-1.620607
998,132.588140,23,15.994720,1.331994,20958.547577,0.271201,0.885971,-1.677411,-0.755032
999,118.062548,13,43.325112,4.889272,14265.164818,-0.024339,-0.264641,-0.299850,0.839537

In [11]:

df_c = df.copy()
df_x = df_c.drop(columns=["주택_가격", "면적", "층수", "역까지_도보시간", "주변_편의시설_점수"], axis=1)
df_x.info()
df_y = df_c["주택_가격"]
df_y.info()
# 독립변수 : 면적_std, 층수_std, 주변_편의시설_점수_std
# 종속변수 : 주택가격

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   면적_std          1000 non-null   float64
 1   층수_std          1000 non-null   float64
 2   주변_편의시설_점수_std  1000 non-null   float64
 3   역까지_도보시간_std    1000 non-null   float64
dtypes: float64(4)
memory usage: 31.4 KB
<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: 주택_가격
Non-Null Count  Dtype
--------------  -----
1000 non-null   float64
dtypes: float64(1)
memory usage: 7.9 KB

In [12]:
print(type(df_x))
print(type(df_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [13]:
# 데이터 분리하기 7:3

train_X, test_X, train_y, test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=42)
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(700, 4) (700,)
(300, 4) (300,)

In [14]:
# 클래스 생성
knr = KNeighborsRegressor()
knr

# 훈련시키기
knr.fit(train_X, train_y)

# 정확도()
train_score = knr.score(train_X, train_y)
test_score = knr.score(test_X, test_y)
gap = train_score - test_score
print(train_score, test_score, gap)

# 예측
pred_train = knr.predict(train_X)
pred_test = knr.predict(test_X)
print(pred_train)
print(pred_test)

0.9816743651469084 0.96995281658901 0.01172154855789842
[ 8960.73170376 10270.3014472  31332.60010137  6486.29434759
 21216.17010535 14537.77974203 36167.74311438  9283.77817098
 14189.51148367 12374.16805122 36141.59501558  5722.42284525
 27134.25533464 11768.90070301  5282.33064168 12883.66423028
 22564.09598331 20510.82351928  6345.55840444 25040.80996333
  9130.44856918 21453.6558786  31641.63158585 12770.80230517
 23010.9627842  36740.91604934 26658.32810127 21879.85899262
 26114.1210662  22598.52559465 18257.8724665   9699.985054
 31052.78512432 22002.74794121 18714.68761223 13224.39714595
  9683.40993029  9749.38218397 31914.80374709 12755.92966279
 10529.78108443 19155.2037734  22370.86583829 37823.20188381
 30665.61778709  3885.59429736 10739.79721221 10959.01644188
  3938.65038649 26903.40678183 10453.0226188  10601.33458079
 10973.88769892  9489.06469372 36803.24906616 19600.64603849
  8081.26929793 30795.81309481 13361.66735748  7010.31050121
 10155.71390232 22699.83296516  9433.57069986 18446.06609492
 21175.28611319 30176.31436555 22633.68303462 30878.60648701
 13573.67630385 14546.62987363 20263.69057123 12907.35221885
 34992.78413601 11704.00224998 30147.3277849  14137.78869949
 14957.58543531 39381.71974616 22239.37849564 13595.38807338
 21662.81309497 13871.35493489 11495.94168175  8847.86704174
 16942.10892211 28627.34842119 33104.77626446  9108.66488728
 30160.1527022   9759.8490479  37404.01010409 13072.9563466
 12214.86275461 11727.76532371 17046.13447331  9244.31825163
 17131.07195711 21195.12244444 12317.7256581  10872.37686348
 19876.80274112 18001.07584786 10390.86013896 39612.41293171
 14589.43031935 10642.71242738 10203.95478459 24943.5788726
 19955.33526279 34991.34855859  4004.71419362 28511.53445896
 12742.47303852 23402.58611429  7737.3171193   7893.54238224
  3482.61889355 26151.6771179   7202.66603205 10931.14345804
  3983.74245767 24385.79718999 14067.47494201  8964.3959012
  8964.3959012   5236.93912989 27042.52727993 20446.07487188
 12822.41819738  4766.7131224  16230.93056001 10801.44381133
  8055.98786475 14689.65516401  8572.07468367  9148.89741178
  9712.44684479  9417.07710266 34094.16819116  7970.61376738
 36024.6818821  11363.5116231  10481.0125223  29533.81564164
  6508.71084212 33785.46649778 36750.63795709 35100.62346112
  6515.42870161 23965.66112638 37080.50717405 29783.89086107
 10096.61382892 30734.17209793 10973.13851263 13182.0342547
 38168.30891001 12006.98605357 35023.02020955 36030.50863918
  2721.25797577 34696.09851061  8376.17460398 14237.36388912
  9373.25896138 28965.20579217 11803.90731691  6057.0569115
 18234.50840408 36964.33994368 22939.41894198 31722.66955145
 16445.97658792 37290.08686138 13355.83955366 22473.88797994
 21746.45166076 39512.91725889  7789.35762564 26821.65472832
 12770.80230517 20513.68473427 22225.07063273 37800.63760059
 20513.68473427 15709.28518544 14349.00278106 13674.40858054
 22640.25278039 30791.66165793 28623.50369278 33748.30619088
  7530.56071874 36820.84367033 30053.68396584 15658.37495004
  6756.38272744  6616.96430582 13637.49695147 12811.14759536
  7297.67017685  7013.92226738 10070.02516385  9176.82940544
 27162.11084064 19949.69622957 23886.0189929  20870.07903791
  4231.15950832  7550.60573614  8992.18401314 24209.18734516
  5602.6967789  37425.49779584 21016.33967629 34744.18836687
 33963.87239532  6224.07256856 30495.54074923 15821.56302908
 14230.28943215 19663.31851389 13865.70967939  8860.85217287
  8740.04003609  9808.48512941  7404.14008731  9980.2644361
  5416.0870895  35435.75447188 28691.92527845 12861.99621352
 30665.61778709 12466.66980135 34143.15733776 18768.59051146
  8369.5029955  37555.99696319 20659.94488618 32793.75179689
 38096.4036071  10441.91168126 27386.4094579  13861.31095925
 30276.40266269 12418.27097816 28406.39248005 12093.3601299
 13566.08260992 36595.31448695 14151.76252824 31476.49817631
  8464.27526105 13100.09010228 12419.60679183 26818.16475912
  7241.43131742 11205.28189666 17200.37339508  6864.11566701
 12375.61949409 14143.89075604 13026.94967136 21374.10096799
 35396.27140751  6057.717351   24840.86566737 20513.68473427
 31696.73678448 38096.4036071   6143.84953955 22652.50465693
 19155.2037734  12568.66195177  9700.50512574 14386.98389013
 10259.24763726 20924.24987533 20010.88705245 31511.97793224
 24398.47766546 29721.30082063  7226.9847663   8586.59702602
  9706.74372945  4858.98972618 33509.46757969 23739.72832686
  7843.69338261  3006.70256232 36921.6280246   4004.71419362
  4454.84038516 11100.10449052 30266.40148925  4409.76044525
  9309.74058436 22773.8791257  27903.30882899 27365.64134633
 30181.92320259 28693.87122606 11409.56704345 38504.70899534
 23890.91408491 35993.59521219  5244.12693588 23826.10515103
 35436.61904496  3864.87231059 33285.1337731   7953.72592623
 10323.72731748 26903.40678183 16431.81949863 15298.52761799
  7989.41178902 11110.93760207 32833.73783942 26837.08889214
 24223.75829221 34785.94879726 30816.39394757 12770.80230517
  9056.34545628  9005.52329985 31373.54679598 27129.17320884
 11336.10790747  7241.43131742 17691.11674103 33704.44702835
  9795.18691472 13779.44202646 11385.43441195  5661.47683701
 16865.19248463 26119.60751308 15938.31633361 24114.01829659
  7449.77930348 10166.53189456  9771.87895285 19069.43643229
  9452.60871022 12344.15657135 17982.46219139 21057.99486269
 14290.47453299 18820.94420436 17287.37035185  9177.12989239
 29820.55019548 29483.69083207 17620.8771168  19076.62627976
 25040.80996333  6937.17336378 24253.09533852 10394.47030093
  6516.59505012 12679.11499159 14211.32889053  8057.08163868
  6362.74802381 31809.16420377  6854.33212256 11514.05202362
 11970.87549455  3006.70256232 11720.36622037 17479.11925443
 33965.22065431 38941.47197701 13294.82603248 21325.11377902
 12107.21002173 21325.6743939  15654.43204395 20565.21718232
 36680.15901688 19180.93390738  5384.26592481 25359.93971411
  9375.79220175  4810.92071202 22797.77542655 33032.86054781
 31605.17318756 38096.4036071  22789.98930035 29007.97822933
 21755.3905507   9609.12153801 19555.7979565   4863.62749072
 10158.95518853 20676.65737046 22436.40472101 21589.29882294
  6636.49364125  7345.29267018 12326.78873388 14829.12590174
 38110.98297515 24498.62195736 12182.79953244 20945.96444076
 26731.39823811 32689.15837665 14215.30038581 23096.56930916
 11412.28461291 16278.19974485 11344.51174311 34670.13924002
 27133.48756941 22077.78197774 16941.6148007   5486.73185693
 22408.81587719 33509.46757969 33271.33006819 24060.83483171
 15043.64950876 33148.50933681 20830.86413443 16333.51515769
  7491.50769136 21332.40368279  7014.4910411  29783.89086107
 21960.08245624 13872.89192732  6688.79466094 32747.36494823
 12955.8315464  25558.29183182 13712.95310258 32138.21973336
 21325.6743939  36246.97767123  4569.43043935 11531.79861655
 33076.24829393 31416.13868924 37982.93706623 33380.80439046
 35443.9590309  20139.46877763  3006.70256232 22427.98815601
 16482.4281286  10176.72142269 29988.47621513 22543.86810163
  8753.14196294 19237.04707809 21325.6743939  11684.50956441
  6694.49420892 28502.93519741 28288.75234495 34009.62341978
 18523.12342125  6894.41561702 27092.29720899 19969.80177577
 21315.31737223  8679.63654864 12719.17719762 33516.16618477
 15362.21225067 19600.64603849 28693.87122606 31849.75424201
 15654.43204395 15938.31633361 10386.55870547 23890.19339421
 11684.50956441 13404.89513237 18880.99237734 16814.73496128
 11662.5371755  18815.69599423 18964.6698157  29629.76886959
  9142.20835093 16828.79924307  7034.17884423 16787.49422602
 21896.60689805 21662.81309497 28190.76490493 37121.30396812
 26390.22850728 28415.01761413  4945.64192463 20009.13022865
 14058.45190021 36476.50073102 32940.6153166  13406.92375521
 20915.31817771 20317.62394189 15347.89138846 12181.74529659
  7992.35268205  3987.39813148  8298.75003     9673.95411258
 34348.46469279 20894.18412985 14509.12600877  7214.41223115
 22637.26901513 18435.18216241 12670.73187812  9130.44856918
 34785.94879726  9550.2307382   6551.16927597 37760.75981213
 14842.44481689 31394.80562106 21917.67954563 39264.55448508
 17578.34711051 21184.87810587 10666.43674505 35343.4586417
 35047.3458664  11576.4030423  30149.63559438 13142.35090319
 22346.09309317  7992.35268205 14836.60995634  6309.41680488
  8549.06415425 21352.51349292  8860.85217287  6812.41518347
 18681.75859817  2870.76200841 10666.43674505 11997.53171469
 25598.8120283  17413.65495671 29419.94236603  6329.46047502
 20620.67982062  8245.18122913 21092.21128217 11244.99040067
 30878.60648701 24626.7248056  10401.11386982 33282.53325576
 22706.16461028 12828.69073012 20167.34356424 22203.35297377
 19663.31851389 14924.03920257 22706.16461028 18465.6789021
 16360.45660899 21504.37710955  6363.15798553  6813.78560546
 19938.87165126  5066.07445832 11087.31380965  8616.08952718
 19281.67638601 38110.98297515 22803.04115635 34072.37482098
 22187.41118265  9777.70619722 10923.73730602  7018.12447046
 31696.73678448 27360.81690831 30956.70183125  3189.55717968
 14753.10786329  7213.13149401 35436.61904496  6567.50358063
 33090.11266639 14383.64885126 33052.24953245  5275.03590434
  7746.74972783 33616.49002046 24604.65651225  6566.70977241
  9769.86655637 11553.16267886 11482.96297921 24114.87475904
 23803.52140404 30495.54074923 26832.38363681  7288.9963068
 36018.81366518  5106.23312323  5786.62865337 20513.68473427
 37121.30396812  4980.76949955 31733.39661713 11742.74578543
 29724.64889289 11221.36215455  7119.40488238 10390.86013896
 21851.17547985 32710.32364682  8174.57600684  5979.77168888
 10242.36845997 20703.39427212 23137.6864498  35343.4586417
  9566.38053953 20674.9886858   6215.59879912  8700.04390587
  6740.93538783 36892.1903956   6634.81947943 38688.42421102
  5282.33064168 11839.87361895 34122.34103359 12069.13134766
  6366.27227445 36622.8329439  18350.04338865  7241.43131742
 22791.722488   26048.01141422 33313.55794276 13277.71836445
 17479.11925443 10460.69232708 16783.43240287  9283.77817098
 23480.97307227  7630.75204394 13005.03102323  7015.08790535
 12825.95840914 22978.22784973 24735.10341531 11747.94841671
 18040.96716751 18653.98511475 20760.48270946 21315.55036354
 17717.53948671 33217.74215024  8980.79628908 10678.55533789
 27023.52844877 28023.41899555 16715.15007606 22729.00305167
 26837.08889214 25533.45787841 23560.37740264  8526.40518219
 17593.49505311 13357.74098408 13143.66195051 14226.35811313
  7488.68042509 23940.61849025  8384.42405947 13892.82388524
  6175.7177143  11762.67899601 11726.90155062 25680.5960179
 21427.69429953  7707.47916175 36630.98338262 14338.00588622
 14055.45839332  4379.74747874 24765.07087518 37614.60317697
 22069.01549151 10026.20705988 24943.5788726  32187.00285455]
[37198.40925841  6131.3100328  21905.65596618 25770.56137867
 24109.54373934  6180.00310726  5953.15287583 27614.44776779
  5535.07249331  8406.835834    7021.89177348 27162.05828338
 10885.03924922  4095.28963119  7229.85679982  7078.51066406
 14467.48988564 15670.90498505  8827.155872   13681.88591338
  7822.37057844  6467.78731605  3006.70256232  5998.03708325
  6844.78927227  6567.50358063 35761.69282475  7871.26267182
 27218.60373399 10272.06970182 20405.53876512  4784.29295237
 11061.36841587  4708.23660533 15628.4036504   9097.85540411
 37760.75981213 18963.32084453 30248.19362124 33238.35724861
  5914.67784874 22456.6933379  12093.78098385 30412.36987305
 25255.08107947 38564.99285431 16404.0368885  15226.68536543
  9769.86655637 31192.64246984 11276.86519993 16423.66700602
 15985.68129205 10988.6816203   8882.4195475  28611.52763773
 12412.4599624  17355.35151575 14747.32547682 11221.36215455
  7544.31659837 21540.41951293  7082.52147016 12266.20289768
 17629.04376338 24462.34732753  8644.48928628  9107.97416181
  4651.01611525  9035.85899318  9782.93019107 14348.17722354
 28950.71455207  7641.92138921 16819.69412531  5132.85083809
 23061.84860727 12419.60679183 10654.50900926 34643.50380633
 38365.17699829 20132.53108905 28838.93895935 32939.19231283
 17820.21900939 12344.15657135 20177.43027949  9930.54598934
 13363.69010741 31980.69015832  7641.92138921 30380.57345569
  7010.31050121 21120.58828963 15247.68331226 20178.54540875
 15728.53035899 12009.29367542 23499.98585125 29037.34731234
  9590.23019361 15183.89450972 38619.8621335  12623.85070487
 11468.80406595  3840.05638029 20460.89725513  7761.1940637
  3995.80698426  9957.69470275 33712.7614918  31610.49566952
 32213.93190004  9130.99076864 10319.99102037  9146.59079115
 19162.63550614 15672.68756847  7943.77259857 16565.97745645
 12770.80230517 28754.65248455 20573.50996874 11286.05224519
 16594.2059915  33730.25873953 14706.29268816 36680.15901688
 35746.36499214 14290.47453299 21067.00301824 24952.1796749
 11170.18168    11534.34782041 34212.94867241 24114.87475904
  6669.60854798 36246.97767123  4117.98478192 29393.71633875
  9727.57114152 17447.75028174 31656.30579799  5384.26592481
 19986.92028645 11215.92830539 29030.09699324  4237.71427105
  3420.25934297  4035.30865349 32877.25551574 21252.63238759
 38450.41561647 14133.92610768 18728.61644723  4115.59661535
 11426.26704198 12840.1627642  34361.85718403 30442.23097136
 31917.57584341 18681.7602578  24957.09783408 14197.16395362
 10433.20692143 10575.51627208 25140.80671074 31475.27911824
 18746.50874236 20513.68473427 29684.30402462 32973.86257187
  4494.51126935 28255.51631142 12589.59811625 23440.99356175
 22292.63552462  9832.96899633 24247.49517736 10666.99421314
 17526.95821593 36602.5258722   8530.28885903 25301.26501141
  7495.5369091  23890.19339421 31831.47170893 12715.38071204
 28846.5072037  28402.96857786 13994.27629663 14778.17643094
 30353.0643694   5901.10653776 24140.38053208  8536.11551412
 13532.92442172 38619.8621335  32443.01437009 13244.98075049
 24376.86990652  3787.36082985 21792.00274116  7024.06212447
 33592.13956527 20571.50216754 12885.65608238 29502.24752208
  3006.70256232 15134.00399012 37860.24604396 29068.75606898
 32001.84804981 38616.81336654 22025.29503056 14664.46998774
  6159.81959138 20453.70358648  7327.26429333 13224.39714595
 10625.94359143 11676.76047581 38096.4036071  35343.4586417
 18528.54821458 21699.91571273  5149.72743821 24146.15023314
 23093.61675395 21633.53772526 22793.32484613 17347.42081785
 27824.47085841  6900.33633903  9121.45732026 22027.78961137
 38450.41561647 26386.47280035 24756.71909073 14097.76490145
  7229.85679982 25040.80996333 19104.42339913 11800.05095271
 10453.0226188   5774.6540725  12864.27737332 13336.25225413
 28441.27378825 27683.01595165  9482.41599019 13332.9983002
 14958.74918503 15134.43445778 36702.86381753 15018.13220501
 29328.20934986  8760.04937541 25327.25470762  6756.38272744
 18815.69599423  5883.04810387 29843.49978737  5028.20063063
 31561.98460524  8502.9161798  36030.14516476 25040.80996333
 12131.74830292 10173.66647248  8029.7814639  28471.15331631
 32535.32791798 23498.72922433 20395.7035991   9903.83598543
 29084.25667936 29533.81564164  3631.52845719 21375.56822161
 24620.32195487 21544.94998323 17270.38447382  4863.62749072
 12689.56618777 27209.92162222  4318.05099997 11443.45939138
 12419.60679183 28107.31324601  6329.46047502 17747.11102757
 20651.85588709 29007.97822933 10378.443846   18198.32451005
  6916.66735261  9843.47319136 28741.59557783  7221.92801817]

In [15]:
# 클래스 생성
lr = LinearRegression()
lr

# 훈련시키기
lr.fit(train_X, train_y)

# 정확도()
train_score = lr.score(train_X, train_y)
test_score = lr.score(test_X, test_y)
gap = train_score - test_score
print(train_score, test_score, gap)

# 예측
pred_train = lr.predict(train_X)
pred_test = lr.predict(test_X)
print(pred_train)
print(pred_test)

0.9667666579420744 0.9686673480370794 -0.001900690095005042
[ 7.87596009e+03  9.18074423e+03  3.04559530e+04  6.76103905e+03
  2.15651390e+04  1.56218834e+04  3.34709478e+04  1.10144698e+04
  1.56390901e+04  1.47661454e+04  3.55752886e+04  4.91981232e+03
  2.62039454e+04  1.34775188e+04  8.16182338e+03  1.41505673e+04
  2.50689064e+04  2.27645221e+04  6.38167900e+03  2.74047430e+04
  7.80456119e+03  2.09931221e+04  3.25879985e+04  1.29076430e+04
  2.35549010e+04  3.49496755e+04  2.89930596e+04  2.19681207e+04
  2.53893967e+04  2.16594599e+04  1.95813907e+04  7.05057751e+03
  2.89155779e+04  2.45924571e+04  1.87146676e+04  1.55384410e+04
  1.10409787e+04  5.95759019e+03  3.16341593e+04  1.41864903e+04
  1.14752551e+04  2.06669186e+04  2.38565307e+04  3.58424387e+04
  2.76905597e+04  2.93973960e+03  1.00909515e+04  1.03837974e+04
  2.34244122e+03  2.80042468e+04  7.71738758e+03  1.15997917e+04
  1.00382958e+04  1.03267777e+04  3.68727603e+04  2.04500482e+04
  7.91606893e+03  3.26124487e+04  1.39191179e+04  3.96637939e+03
  7.12476784e+03  2.70145483e+04  9.73008349e+03  2.02147631e+04
  2.35527674e+04  3.16075600e+04  2.55377073e+04  3.07327566e+04
  1.64436809e+04  1.67585905e+04  2.15298382e+04  1.74926558e+04
  3.45523152e+04  1.23760803e+04  3.09247275e+04  1.66494140e+04
  1.77497721e+04  3.73751699e+04  2.46960895e+04  1.06734859e+04
  2.31481726e+04  1.25851595e+04  1.52525085e+04  8.88255271e+03
  2.02694736e+04  3.03276955e+04  3.18295923e+04  8.64159554e+03
  2.69586363e+04  1.13297730e+04  3.69540321e+04  1.53496896e+04
  1.39955731e+04  1.34592618e+04  1.81619997e+04  1.13973570e+04
  2.04799733e+04  2.27455852e+04  1.50584511e+04  1.19728995e+04
  2.06726996e+04  2.12055482e+04  1.03935450e+04  3.79242556e+04
  1.66622573e+04  1.16740485e+04  5.95286999e+03  2.70212845e+04
  2.26516783e+04  3.34316316e+04  9.54057219e+02  2.86720350e+04
  1.29414731e+04  2.56895685e+04  6.05358943e+03  5.57136899e+03
  3.46945340e+02  2.62421459e+04  6.51831621e+03  9.44899809e+03
  2.35268883e+03  2.55581050e+04  1.50797204e+04  8.84679220e+03
  9.60199656e+03  3.13662780e+03  2.68573483e+04  2.28015025e+04
  1.50066642e+04 -4.95739321e+02  1.86806137e+04  1.34006503e+04
  7.51482938e+03  1.72921188e+04  1.01727519e+04  9.89228888e+03
  8.99800156e+03  9.86008490e+03  3.43122651e+04  1.10434549e+04
  3.37689617e+04  1.29413825e+04  1.02638374e+04  2.90178163e+04
  2.23449836e+03  3.27210258e+04  3.55826905e+04  3.46205865e+04
  5.39892904e+03  2.58045818e+04  3.59298146e+04  3.01551244e+04
  1.25313860e+04  2.85411414e+04  1.09265679e+04  1.45549694e+04
  3.77779958e+04  1.02832658e+04  3.39406395e+04  3.33641286e+04
 -1.49064697e+03  3.60955204e+04  7.58649683e+03  1.64131524e+04
  8.49173349e+03  2.97160902e+04  1.42832898e+04  3.50522438e+03
  1.85228217e+04  3.21700780e+04  2.31538968e+04  3.15546250e+04
  1.99680731e+04  3.71981630e+04  1.56580497e+04  2.51429601e+04
  2.45964041e+04  3.63704802e+04  7.06338402e+03  2.51527200e+04
  1.19167442e+04  2.08402432e+04  2.40716178e+04  3.55483666e+04
  2.40666484e+04  1.66656704e+04  1.60429655e+04  1.69626056e+04
  2.70291520e+04  2.80676106e+04  2.83889584e+04  3.28373792e+04
  4.74489495e+03  3.60277770e+04  3.07029898e+04  1.87085422e+04
  2.71587199e+03  3.35354464e+03  1.52502555e+04  1.41811182e+04
  3.96541266e+03  1.84403395e+03  8.49041639e+03  9.32391013e+03
  2.90364651e+04  2.33240298e+04  2.53680789e+04  2.44861539e+04
  6.40280450e+02  3.32207991e+03  1.22087732e+04  2.54246346e+04
  1.15565594e+02  3.52575700e+04  2.22791068e+04  3.50227129e+04
  3.34368957e+04  4.27828727e+03  2.80821625e+04  1.76824935e+04
  1.67945591e+04  2.08396409e+04  1.54741517e+04  7.89535530e+03
  8.71384896e+03  9.29228293e+03  4.34132022e+03  7.45277862e+03
  8.67376900e+02  3.42550791e+04  2.89803337e+04  1.59962283e+04
  2.68019314e+04  1.58662796e+04  3.18133722e+04  1.98425313e+04
  8.40926447e+03  3.60321291e+04  2.13201979e+04  3.27378409e+04
  3.49911430e+04  1.10674726e+04  2.81260585e+04  1.54304347e+04
  2.99389637e+04  1.18979147e+04  2.90960045e+04  1.23305986e+04
  1.66123018e+04  3.53525169e+04  1.67152139e+04  3.09120720e+04
  8.70701092e+03  1.51695733e+04  1.16442627e+04  2.72442059e+04
  8.37942435e+03  8.77524100e+03  1.88427086e+04  6.23562191e+03
  1.39790540e+04  1.67726153e+04  1.51613305e+04  2.41045942e+04
  3.35875953e+04  2.31413638e+03  2.32247418e+04  2.32537460e+04
  3.02434126e+04  3.48513393e+04  4.46008175e+03  2.43852156e+04
  2.10526502e+04  1.44050417e+04  1.06480729e+04  1.79516868e+04
  7.24601579e+03  2.00019602e+04  2.24717851e+04  3.30697348e+04
  2.59490022e+04  2.88891432e+04  6.56370774e+03  8.08452866e+03
  6.78203116e+03  9.21045851e+02  3.11279702e+04  2.42731353e+04
  5.34928138e+03  3.42799988e+03  3.51990210e+04  2.55295956e+03
 -6.45455421e+02  1.14686889e+04  2.70934702e+04  1.03482107e+03
  7.20694320e+03  2.61488891e+04  2.84251758e+04  2.89117936e+04
  2.94955020e+04  2.82657150e+04  1.11646651e+04  3.80497826e+04
  2.32171464e+04  3.48655358e+04  4.81997385e+03  2.56399275e+04
  3.34869813e+04 -1.35658194e+02  3.08615135e+04  7.89349229e+03
  1.08171092e+04  3.11474697e+04  1.79678990e+04  1.61797259e+04
  3.45471115e+03  1.02964281e+04  3.27609453e+04  2.55849202e+04
  2.59213439e+04  3.32699824e+04  2.80103361e+04  1.24710645e+04
  6.94051384e+03  4.44695031e+03  3.04169263e+04  2.77283309e+04
  1.34410029e+04  7.83661486e+03  1.95963222e+04  3.35141670e+04
  9.93486471e+03  1.56132878e+04  9.48421784e+03  1.01375619e+03
  1.85776920e+04  2.43393954e+04  1.44992810e+04  2.51181913e+04
  5.42778651e+03  1.10794632e+04  1.01625511e+04  2.14812013e+04
  6.44408234e+03  1.37097264e+04  1.95627905e+04  2.27550085e+04
  1.69796672e+04  2.03131402e+04  1.90366473e+04  8.48077857e+03
  3.17234956e+04  2.77467633e+04  2.00007807e+04  2.17709868e+04
  2.49488002e+04  2.18144519e+03  2.56586754e+04  1.14735826e+04
  3.44079534e+03  1.56670169e+04  1.62628101e+04  3.75003104e+03
  6.37336709e+03  3.04486009e+04  7.12475546e+03  1.23644406e+04
  1.26850622e+04  1.87832764e+03  1.14589213e+04  2.05356626e+04
  3.20781537e+04  3.97485427e+04  1.13720160e+04  2.13689134e+04
  1.24495618e+04  2.48687970e+04  1.74551808e+04  2.42791178e+04
  3.56026185e+04  1.93012996e+04  2.74678986e+03  2.63887746e+04
  5.52924046e+03  5.16787927e+02  2.56911674e+04  3.31619813e+04
  2.99137614e+04  3.52939269e+04  2.42290742e+04  2.82018463e+04
  2.29012211e+04  8.67840750e+03  2.48346599e+04  1.25751426e+03
  1.25594602e+04  2.35428618e+04  2.29420729e+04  2.35835700e+04
  5.11300313e+03  5.50095734e+03  1.26570488e+04  1.55994148e+04
  3.85451413e+04  2.62897546e+04  1.38925165e+04  2.25943137e+04
  2.79655420e+04  3.07128044e+04  1.56605855e+04  2.53970806e+04
  1.19858959e+04  1.79095505e+04  1.12102380e+04  3.39349269e+04
  2.90528469e+04  2.36389429e+04  1.87399821e+04  3.87273325e+03
  2.58600065e+04  3.34839622e+04  3.15758902e+04  2.64009117e+04
  1.81316934e+04  3.15643528e+04  2.09396164e+04  1.87636699e+04
  5.63756402e+03  2.35479345e+04  6.82246717e+03  3.15736852e+04
  1.99679960e+04  1.54386483e+04  5.13303048e+03  3.06168522e+04
  1.24129082e+04  2.54423716e+04  1.73282879e+04  2.95514299e+04
  2.29167887e+04  3.27176962e+04  5.93381789e+02  9.97381709e+03
  3.12245693e+04  2.80504150e+04  3.60783230e+04  3.13225037e+04
  3.44831891e+04  2.16622799e+04  4.04530573e+03  2.39295561e+04
  1.85450700e+04  1.19007194e+04  3.07128815e+04  2.41810681e+04
  7.16623357e+03  1.69186360e+04  2.32131499e+04  1.43398657e+04
  4.31105216e+03  2.85619395e+04  2.80828847e+04  3.34573669e+04
  2.09370162e+04  7.52524866e+03  2.43267123e+04  2.27115630e+04
  2.33638715e+04  1.03683161e+04  1.43528480e+04  3.34495558e+04
  1.55451473e+04  2.40977538e+04  3.38596909e+04  3.11748781e+04
  1.70256694e+04  1.74717165e+04  1.04399581e+04  2.26199289e+04
  1.21408269e+04  1.54220324e+04  1.96321451e+04  1.88650038e+04
  1.01175045e+04  1.84819559e+04  2.00467768e+04  2.63573353e+04
  7.88743544e+03  1.93983553e+04  9.34236266e+03  1.93374798e+04
  2.27527555e+04  2.37968079e+04  2.97600489e+04  3.32221059e+04
  2.60361041e+04  2.93545490e+04  6.24570842e+03  2.13688177e+04
  1.60501427e+04  3.57533567e+04  3.00422602e+04  1.36359883e+04
  2.14316689e+04  2.09932083e+04  1.88670270e+04  1.34100345e+04
  8.73271738e+03 -8.70654849e+02  7.17042138e+03  1.00376826e+04
  3.07709018e+04  2.25910365e+04  1.76665071e+04  7.29186409e+03
  2.37162640e+04  1.92645549e+04  1.53683383e+04  6.01953359e+03
  3.44442315e+04  6.44657742e+03  5.48807240e+03  3.71000174e+04
  1.48655049e+04  3.09343820e+04  2.44212108e+04  3.62118600e+04
  1.76310569e+04  2.40239313e+04  1.19112238e+04  3.28296907e+04
  3.11244533e+04  1.31921346e+04  2.91356906e+04  1.34333205e+04
  2.51761262e+04  6.45509627e+03  1.78800481e+04  1.56889504e+03
  8.47326285e+03  2.10639357e+04  1.10810923e+04  4.27968869e+03
  1.71469396e+04  8.24436896e+00  1.08919550e+04  1.31595351e+04
  2.73238629e+04  1.55819930e+04  3.01678587e+04  1.94458621e+03
  2.17588468e+04  7.54625465e+03  2.06728529e+04  1.40687135e+04
  3.05562189e+04  2.52459770e+04  1.18270246e+04  3.22443501e+04
  2.48603822e+04  1.26351091e+04  2.09926202e+04  2.43848035e+04
  2.03791046e+04  1.85482045e+04  2.41980834e+04  2.24235137e+04
  1.80924094e+04  2.33444206e+04  6.55598368e+03  9.22489367e+03
  2.37735835e+04  3.40640473e+03  1.52833377e+04  8.17023903e+03
  2.11795238e+04  3.64138260e+04  2.29773476e+04  3.26867748e+04
  2.62335501e+04  8.16527915e+03  1.00541672e+04  3.90571107e+03
  3.25656514e+04  2.86322010e+04  2.92403823e+04  1.69183143e+03
  1.70572947e+04  6.31952220e+03  3.19717778e+04  1.92249826e+03
  3.24657727e+04  1.51797919e+04  3.06116628e+04  6.27077839e+03
  7.95805800e+03  3.24391655e+04  2.49515219e+04  2.50915201e+03
  1.18804218e+04  1.07284631e+04  1.19435313e+04  2.65078132e+04
  2.58890180e+04  3.37002489e+04  3.00498998e+04  3.57129508e+03
  3.42255791e+04  2.79811830e+03  2.59266732e+03  2.25631672e+04
  3.28734087e+04  1.58589354e+03  3.18265547e+04  1.06592987e+04
  2.90963819e+04  9.78010011e+03  3.52472949e+03  1.15843917e+04
  2.24406640e+04  3.04558655e+04  7.78412742e+03  1.18029192e+03
  5.86824137e+03  2.14775867e+04  2.21936526e+04  3.35248134e+04
  8.96785607e+03  2.19327290e+04  3.15220444e+03  7.75459720e+03
  2.93586003e+03  3.56373651e+04  3.61842914e+03  3.61444300e+04
  5.50927511e+03  1.06717399e+04  3.54632861e+04  1.38366452e+04
  2.75876945e+03  3.44811143e+04  2.26429959e+04  5.74521854e+03
  2.31125779e+04  2.72974060e+04  3.06346481e+04  1.50072971e+04
  1.76449300e+04  6.18919873e+03  2.01251892e+04  8.54397053e+03
  2.46002418e+04  6.43302151e+03  1.65132539e+04  8.68016755e+03
  1.57174666e+04  2.46811908e+04  2.35462363e+04  1.38896281e+04
  1.79897578e+04  2.04700799e+04  2.19563823e+04  2.27952727e+04
  1.90828210e+04  3.30216390e+04  6.05786463e+03  1.06062942e+04
  2.58839192e+04  2.63403256e+04  1.90348108e+04  2.23827917e+04
  2.54199594e+04  2.74974386e+04  2.52536943e+04  8.56270230e+03
  1.61330643e+04  1.43694270e+04  1.39050331e+04  1.52865297e+04
  8.41194251e+03  2.24754906e+04  8.88716790e+03  1.65953165e+04
  7.93516905e+02  7.19373607e+03  7.75380566e+03  2.49160158e+04
  2.55115691e+04  5.38157357e+03  3.72067654e+04  1.77085150e+04
  1.62857691e+04  1.97759556e+03  2.56048098e+04  3.47834629e+04
  2.35086614e+04  1.10715074e+04  2.62178626e+04  3.15646494e+04]
[ 3.52567436e+04  2.60750036e+03  2.42395876e+04  2.92755337e+04
  2.57842328e+04  5.87056019e+03  3.31916850e+02  2.75125308e+04
  5.84065789e+03  5.39968821e+03  6.82355735e+03  2.81668977e+04
  1.24701839e+04  3.58424628e+03  3.28034461e+03  1.93400828e+03
  1.38500045e+04  1.71536815e+04  8.48584368e+03  1.61364484e+04
  5.29650715e+03  3.47998400e+03  3.15910069e+02  2.37666844e+03
  4.28515649e+03  2.87220304e+03  3.48099451e+04  4.07913381e+03
  2.81218824e+04  9.86135404e+03  2.36690314e+04  1.60828282e+03
  1.33297138e+04  4.20104063e+03  1.58423087e+04  6.42405282e+03
  3.65895813e+04  2.06140201e+04  3.17987183e+04  3.24278448e+04
  3.01986410e+03  2.22275526e+04  1.30330149e+04  3.27663490e+04
  2.69705369e+04  3.53741092e+04  1.77066612e+04  1.95112139e+04
  1.00274067e+04  2.99921549e+04  9.45280188e+03  1.92353861e+04
  1.80249698e+04  8.70558724e+03  8.22339177e+03  2.90135351e+04
  1.50349530e+04  1.73854321e+04  1.59693824e+04  1.59179541e+04
  7.16885588e+03  2.31311344e+04  3.37503505e+03  1.34823974e+04
  2.11969525e+04  2.55985940e+04  9.12309464e+03  9.98342014e+03
  1.68524714e+03  9.99082634e+03  9.65889853e+03  1.79543014e+04
  2.78199512e+04  6.10936621e+03  1.77759766e+04  8.63831145e+02
  2.14695806e+04  1.46571321e+04  1.07160528e+04  3.54378569e+04
  3.66666070e+04  2.16006317e+04  2.88203373e+04  2.83346112e+04
  2.25467893e+04  1.41727307e+04  2.26590175e+04  8.30542350e+03
  1.52959492e+04  3.13549341e+04  1.96714735e+03  2.79621728e+04
  9.07121919e+03  2.23807335e+04  1.33708399e+04  1.96691690e+04
  1.53921955e+04  1.28824122e+04  2.54228514e+04  2.89820343e+04
  8.60479551e+03  1.62610805e+04  3.97928319e+04  1.45183950e+04
  1.35162504e+04  4.08891818e+03  2.18093758e+04  7.69476000e+03
  6.56088657e+02  6.67085354e+03  3.34847238e+04  3.13783500e+04
  3.33173100e+04  6.46328023e+03  5.91041887e+03  8.20297904e+03
  1.90584960e+04  1.70484691e+04  7.49382557e+03  1.80500329e+04
  1.32747157e+04  2.79835521e+04  2.46617603e+04  1.19625455e+04
  1.84378184e+04  3.54847715e+04  1.74266962e+04  3.59252173e+04
  3.58465020e+04  1.74690140e+04  2.52668377e+04  2.64283051e+04
  6.32896765e+03  1.41647531e+04  3.27710268e+04  2.00647756e+04
  2.83697100e+03  3.45872969e+04  2.10822285e+03  2.77142961e+04
  9.54720149e+03  2.14270518e+04  3.12305246e+04  6.50217822e+02
  2.34193356e+04  1.36170150e+04  3.02700442e+04  4.87668199e+03
 -1.49040930e+03  1.11208649e+03  2.97395407e+04  2.44923300e+04
  3.41575945e+04  1.46197041e+04  2.19178607e+04  7.61092603e+02
  1.22023986e+04  1.23060446e+04  3.42008063e+04  2.92652160e+04
  3.01624762e+04  1.92749172e+04  2.79793575e+04  1.35873797e+04
  1.03382326e+04  9.54417917e+03  2.79592965e+04  3.51859175e+04
  2.23306095e+04  2.39355515e+04  3.02191363e+04  3.19783895e+04
  9.26386463e+02  2.85508213e+04  1.44513627e+04  2.59443352e+04
  2.25442792e+04  7.98096228e+03  2.63170168e+04  1.19897685e+04
  1.88618051e+04  3.19029622e+04  8.08089403e+03  2.43941465e+04
  4.88059236e+03  2.49647378e+04  3.14433421e+04  1.42687472e+04
  2.73553205e+04  2.92371144e+04  1.45696235e+04  1.80340747e+04
  2.85937415e+04  5.46786253e+03  2.88454270e+04  4.65293490e+03
  1.35355573e+04  3.79913299e+04  3.21863944e+04  1.60877095e+04
  2.54886586e+04 -3.74232378e+02  2.59021457e+04  5.35150660e+03
  3.30435388e+04  2.22110474e+04  1.12389034e+04  2.73108681e+04
  8.38090721e+00  1.71824238e+04  3.64193736e+04  3.02997600e+04
  2.97719714e+04  3.69800741e+04  2.28029747e+04  1.58433964e+04
  1.06254973e+03  2.19178423e+04  4.73155591e+03  1.38911469e+04
  1.21949782e+04  9.24053917e+03  3.48927635e+04  3.23750790e+04
  1.79916224e+04  2.44327669e+04  6.99693376e+03  2.78394133e+04
  2.30790086e+04  2.40120751e+04  2.77172683e+04  1.95249748e+04
  2.68288154e+04  3.90138893e+03  7.52547245e+03  2.49099684e+04
  3.88217897e+04  2.70932186e+04  2.45811695e+04  1.65316181e+04
  7.98148336e+03  2.30917019e+04  2.17170704e+04  1.39843233e+04
  8.46277124e+03  5.92251652e+03  1.44849124e+04  1.55283760e+04
  2.89486174e+04  2.79023855e+04  1.08486431e+04  1.21210299e+04
  1.61361955e+04  1.47733257e+04  3.38079209e+04  1.65423401e+04
  3.03770693e+04  1.01053745e+04  2.47952882e+04  3.97012191e+03
  1.98453710e+04  3.90820888e+03  2.81304567e+04  1.02232265e+03
  3.03525361e+04  7.68465987e+03  3.53838067e+04  2.96319121e+04
  1.33074663e+04  9.17945127e+03  1.07479481e+04  2.74602826e+04
  3.05059192e+04  2.19620358e+04  2.20203434e+04  9.18179812e+03
  2.93105533e+04  2.91551719e+04  1.56456366e+03  2.30249110e+04
  3.25873831e+04  2.40623446e+04  1.94796859e+04  5.26628090e+02
  1.38387713e+04  2.74322347e+04  1.92997787e+03  1.04956777e+04
  1.28196837e+04  2.74482153e+04  4.54105510e+03  2.06190577e+04
  2.44411816e+04  2.78828114e+04  1.26867920e+04  2.01751727e+04
  4.72660038e+03  1.22488274e+04  2.89998110e+04  4.68177827e+03]